import os
import torch
import numpy as np
import matplotlib.pyplot as plt
from captum.attr import visualization as viz

def plot_attributions(original_image, attributions_dict, save_path, true_label, pred_prob):
    """
    Plots the original image alongside the attributions generated by different methods.
    
    Args:
        original_image (torch.Tensor): The original input tensor [3, H, W]
        attributions_dict (dict): Dictionary mapping method name to its attribution tensor.
        save_path (str): File path to save the generated plot.
        true_label (int): Ground truth label.
        pred_prob (float): Model's predicted probability for the positive class.
    """
    num_methods = len(attributions_dict)
    fig, axes = plt.subplots(1, num_methods + 1, figsize=(5 * (num_methods + 1), 5))
    
    # 1. Plot Original Image (denormalized generically/clipped to [0,1])
    orig_np = np.transpose(original_image.cpu().numpy(), (1, 2, 0))
    orig_np = np.clip(orig_np, 0, 1)
    
    axes[0].imshow(orig_np)
    axes[0].set_title(f"Original\nTrue: {true_label} | Pred Prob: {pred_prob:.3f}")
    axes[0].axis('off')
    
    # 2. Plot Attributions iteratively
    for idx, (method_name, attr_tensor) in enumerate(attributions_dict.items()):
        ax = axes[idx + 1]
        
        # Captum expects numpy arrays formatted as (H, W, C)
        # Squeeze batch dim if present, then transpose
        if attr_tensor.ndimension() == 4:
            attr_tensor = attr_tensor.squeeze(0)
            
        # For methods that return gradients across 3 channels (like IG), we take the sum over channels mapping to grayscale intensity
        attr_np = np.transpose(attr_tensor.numpy(), (1, 2, 0))
        
        if method_name == "Grad-CAM":
            # Grad-CAM usually returns a 1-channel spatial map directly
            if attr_np.shape[-1] == 1:
                # Viz requires (H, W, 1) or (H,W,3)
                pass 
        else:
            # For pixel-level methods, sum absolute gradients across channels and expand dims
            attr_np = np.sum(np.abs(attr_np), axis=-1, keepdims=True)

        # Use Captum's built-in visualization utility for standardized overlay plotting
        viz.visualize_image_attr(
            attr_np,
            orig_np,
            method="blended_heat_map",
            sign="absolute_value",
            show_colorbar=True,
            title=f"{method_name} Attribution",
            plt_fig_axis=(fig, ax),
            use_pyplot=False
        )

    plt.tight_layout()
    os.makedirs(os.path.dirname(save_path), exist_ok=True)
    plt.savefig(save_path, dpi=150)
    plt.close(fig)

import cv2

def generate_annotated_image(original_image, attr_tensor, save_path, threshold=0.6, 
                              secondary_attrs=None):
    """
    Clinical-grade bounding box localization using multi-source attribution fusion,
    Gaussian smoothing, Otsu adaptive thresholding, and morphological cleanup.
    
    Args:
        original_image (torch.Tensor): The original input tensor [3, H, W]
        attr_tensor (torch.Tensor): Primary attribution heatmap (SAS)
        save_path (str): File path to save the annotated image
        threshold (float): Fallback quantile threshold (used if Otsu fails)
        secondary_attrs (list): Optional list of secondary attribution tensors (IG, Occlusion)
                                for multi-method consensus fusion.
    Returns:
        float: the percentage area of the annotated regions relative to the image size.
    """
    orig_np = np.transpose(original_image.cpu().numpy(), (1, 2, 0))
    orig_np = np.clip(orig_np, 0, 1)
    
    # --- Step 1: Build the attribution heatmap ---
    def attr_to_2d(at):
        if at.ndimension() == 4:
            at = at.squeeze(0)
        a = at.cpu().numpy()
        if a.shape[0] == 3:
            a = np.sum(np.abs(a), axis=0)
        elif a.ndim == 3 and a.shape[-1] == 1:
            a = a.squeeze(-1)
        elif a.ndim == 3 and a.shape[0] == 1:
            a = a.squeeze(0)
        a = np.abs(a)
        if a.max() > 0:
            a = a / a.max()
        return a.astype(np.float32)
    
    primary_map = attr_to_2d(attr_tensor)
    
    # --- Step 2: Multi-method consensus fusion (if available) ---
    if secondary_attrs and len(secondary_attrs) > 0:
        # Resize all maps to match primary, then multiply (intersection = agreement)
        fused = primary_map.copy()
        for sec_attr in secondary_attrs:
            sec_map = attr_to_2d(sec_attr)
            if sec_map.shape != primary_map.shape:
                sec_map = cv2.resize(sec_map, (primary_map.shape[1], primary_map.shape[0]))
            fused = fused * sec_map  # Multiplicative fusion = consensus only
        # Re-normalize
        if fused.max() > 0:
            fused = fused / fused.max()
        heatmap = fused
    else:
        heatmap = primary_map
    
    # --- Step 3: Gaussian blur to smooth out pixel-level noise ---
    kernel_size = max(15, heatmap.shape[0] // 16) | 1  # Must be odd
    heatmap_smooth = cv2.GaussianBlur(heatmap, (kernel_size, kernel_size), 0)
    
    # --- Step 4: Adaptive thresholding (Otsu) ---
    heatmap_uint8 = (heatmap_smooth * 255).astype(np.uint8)
    otsu_val, thresh_img = cv2.threshold(heatmap_uint8, 0, 255, cv2.THRESH_BINARY + cv2.THRESH_OTSU)
    
    # If Otsu gives a very low threshold (too much highlighted), use quantile fallback
    if otsu_val < 50:
        thresh_val = np.quantile(heatmap_uint8, threshold)
        _, thresh_img = cv2.threshold(heatmap_uint8, int(thresh_val), 255, cv2.THRESH_BINARY)
    
    # --- Step 5: Morphological cleanup ---
    morph_kernel = cv2.getStructuringElement(cv2.MORPH_ELLIPSE, (7, 7))
    thresh_img = cv2.morphologyEx(thresh_img, cv2.MORPH_CLOSE, morph_kernel, iterations=2)  # Fill gaps
    thresh_img = cv2.morphologyEx(thresh_img, cv2.MORPH_OPEN, morph_kernel, iterations=1)   # Remove noise
    
    # --- Step 6: Contour detection and drawing ---
    contours, _ = cv2.findContours(thresh_img, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
    
    canvas = (orig_np * 255).astype(np.uint8).copy()
    canvas = cv2.cvtColor(canvas, cv2.COLOR_RGB2BGR)
    
    total_area = float(canvas.shape[0] * canvas.shape[1])
    min_area = total_area * 0.02  # Minimum 2% of image to avoid tiny noise regions
    annotated_area = 0.0
    
    if len(contours) > 0:
        spatial_descriptors = []
        # Filter by minimum area and sort descending
        valid_contours = [c for c in contours if cv2.contourArea(c) >= min_area]
        valid_contours = sorted(valid_contours, key=cv2.contourArea, reverse=True)
        
        colors = [(0, 255, 255), (0, 200, 200), (0, 150, 150)]  # Yellow shades
        labels = ["Primary Region", "Secondary Region", "Tertiary Region"]
        
        for i, c in enumerate(valid_contours[:3]):
            area = cv2.contourArea(c)
            annotated_area += area
            color = colors[min(i, len(colors)-1)]
            
            # Draw a fitted rotated bounding rectangle (tighter than axis-aligned)
            rect = cv2.minAreaRect(c)
            box = cv2.boxPoints(rect)
            box = np.intp(box)
            cv2.drawContours(canvas, [box], 0, color, 2)
            
            # Also draw the precise contour outline
            cv2.drawContours(canvas, [c], -1, color, 1)
            
            # Label with centroid
            M = cv2.moments(c)
            if M["m00"] != 0:
                cX = int(M["m10"] / M["m00"])
                cY = int(M["m01"] / M["m00"])
            else:
                x, y, w, h = cv2.boundingRect(c)
                cX, cY = x + w//2, y + h//2
                
            # Maps coordinates to medical quadrant text definitions
            y_ratio = cY / canvas.shape[0]
            x_ratio = cX / canvas.shape[1]
            if y_ratio < 0.33:
                vert = "Superior"
            elif y_ratio > 0.66:
                vert = "Inferior"
            else:
                vert = "Mid"
                
            if x_ratio < 0.33:
                horiz = "Left Lateral"
            elif x_ratio > 0.66:
                horiz = "Right Lateral"
            else:
                horiz = "Medial"
                
            descriptor = f"{vert} {horiz} Region"
            if descriptor not in spatial_descriptors:
                spatial_descriptors.append(descriptor)
            
            # Arrow from corner to centroid
            arrow_x = max(10, min(cX - 50, canvas.shape[1] - 60))
            arrow_y = max(25, cY - 50)
            cv2.arrowedLine(canvas, (arrow_x, arrow_y), (cX, cY), (0, 0, 255), 2, tipLength=0.25)
            
            label = labels[min(i, len(labels)-1)]
            area_pct = (area / total_area) * 100
            cv2.putText(canvas, f"{label} ({area_pct:.1f}%)", 
                       (max(5, arrow_x - 10), max(15, arrow_y - 8)),
                       cv2.FONT_HERSHEY_SIMPLEX, 0.35, (0, 0, 255), 1)
    
    os.makedirs(os.path.dirname(save_path), exist_ok=True)
    cv2.imwrite(save_path, canvas)
    
    return (annotated_area / total_area if total_area > 0 else 0.0), spatial_descriptors if len(contours) > 0 else []


def generate_clinical_summary(prediction_prob, roc_area_pct, disease_name="Unknown"):
    """
    Generates a human-friendly English text summary explaining the model's logic.
    
    Args:
        prediction_prob (float): The final model probability (0-1)
        roc_area_pct (float): The percentage of the image covered by the primary Region of Concern.
        disease_name (str): The target disease being diagnosed.
    """
    diagnosis = "POSITIVE" if prediction_prob >= 0.5 else "NEGATIVE"
    confidence_str = f"{prediction_prob:.2%}" if diagnosis == "POSITIVE" else f"{(1 - prediction_prob):.2%}"
    
    summary = f"The automated diagnostic model predicts {diagnosis} for {disease_name} with {confidence_str} confidence. "
    
    if diagnosis == "POSITIVE":
        if roc_area_pct > 0.4:
            summary += f"Severe structural anomalies detected, spanning a massive {roc_area_pct:.1%} of the scan visualization area."
        elif roc_area_pct > 0.1:
            summary += f"Primary focal evidence was identified in a localized region comprising {roc_area_pct:.1%} of the visualization area."
        else:
            summary += f"The diagnostic conclusion was driven by minor, highly-concentrated features (occupying {roc_area_pct:.1%} of visual area)."
    else:
        summary += "The model found no significant focal features indicative of abnormal pathology."
        
    return summary

def generate_high_res_annotation(original_image, high_res_tensor, save_path, threshold=0.85):
    """
    Creates a hyper-detailed overlay using a high-resolution attribution map (e.g. Integrated Gradients).
    Instead of a blurry blob bounding box, this explicitly traces the sharp anatomical edges
    the model is looking at, using polygonal approximations for distinct boundaries.
    """
    orig_np = np.transpose(original_image.cpu().numpy(), (1, 2, 0))
    orig_np = np.clip(orig_np, 0, 1)
    
    # Process IG or pixel-level tensor
    if high_res_tensor.ndimension() == 4:
        high_res_tensor = high_res_tensor.squeeze(0)
        
    attr_np = high_res_tensor.cpu().numpy()
    
    if attr_np.shape[0] == 3:
        attr_np = np.sum(np.abs(attr_np), axis=0)
    elif attr_np.ndim == 3 and attr_np.shape[-1] == 1:
        attr_np = attr_np.squeeze(-1)
    elif attr_np.ndim == 3 and attr_np.shape[0] == 1:
        attr_np = attr_np.squeeze(0)
        
    attr_np = np.abs(attr_np)
    if attr_np.max() > 0:
        attr_np = attr_np / attr_np.max()
        
    heatmap_uint8 = (attr_np * 255).astype(np.uint8)
    
    # Very high threshold to isolate only the exact highest-driving pixels (distinct regions)
    thresh_val = np.quantile(heatmap_uint8, threshold)
    _, thresh_img = cv2.threshold(heatmap_uint8, thresh_val, 255, cv2.THRESH_BINARY)
    
    # Morphological closing to connect nearby sharp pixels into a solid distinct anatomical shape
    kernel = np.ones((3,3), np.uint8)
    thresh_img = cv2.morphologyEx(thresh_img, cv2.MORPH_CLOSE, kernel)
    
    contours, _ = cv2.findContours(thresh_img, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
    
    canvas = (orig_np * 255).astype(np.uint8).copy()
    canvas = cv2.cvtColor(canvas, cv2.COLOR_RGB2BGR)
    
    if len(contours) > 0:
        contours = sorted(contours, key=cv2.contourArea, reverse=True)
        # Point to the top 4 most distinct detailed regions
        for i, c in enumerate(contours[:4]):
            if cv2.contourArea(c) < 15: # Ignore single stray pixels
                continue
                
            # Distinct outline using a polygonal approximation for a harsh, exact mechanical look
            epsilon = 0.01 * cv2.arcLength(c, True)
            approx = cv2.approxPolyDP(c, epsilon, True)
            
            # Draw the sharp distinct path
            cv2.drawContours(canvas, [approx], -1, (255, 0, 255), 2) # Magenta sharp outline
            
            # Point an exact arrow
            M = cv2.moments(c)
            if M["m00"] != 0:
                cX = int(M["m10"] / M["m00"])
                cY = int(M["m01"] / M["m00"])
            else:
                x, y, w, h = cv2.boundingRect(c)
                cX = x + w//2
                cY = y + h//2
                
            # Arrows coming from slightly above-left
            start_x, start_y = max(5, cX - 35), max(5, cY - 35)
            cv2.arrowedLine(canvas, (start_x, start_y), (cX, cY), (0, 255, 0), 2, tipLength=0.4)
            
            if i == 0:
                label_y = max(10, start_y - 8)
                cv2.putText(canvas, "EXACT DETAIL", (start_x, label_y), 
                            cv2.FONT_HERSHEY_SIMPLEX, 0.35, (0, 255, 0), 1)

    os.makedirs(os.path.dirname(save_path), exist_ok=True)
    cv2.imwrite(save_path, canvas)

