import React, { useState, useRef, useCallback, useEffect } from 'react';
import {
  View, Text, TextInput, TouchableOpacity, Image, ScrollView,
  StyleSheet, ActivityIndicator, StatusBar, Animated,
  Keyboard, Alert, Dimensions, Platform, Modal, Switch,
  NativeModules, NativeEventEmitter,
} from 'react-native';

// Native PyTorch Mobile bridge for on-device inference
const { PytorchBridge } = NativeModules;
import * as ImagePicker from 'expo-image-picker';
import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';
import RNFS from 'react-native-fs';

const { width: SCREEN_W } = Dimensions.get('window');

// ═══════════════════════════════════════════════════════════════════════════════
// FEATURE 8: LANGUAGE LOCALIZATION (EN, HI, TA, BN)
// ═══════════════════════════════════════════════════════════════════════════════
const STRINGS = {
  en: {
    appTitle: 'Offline Diagnostics Node',
    appSub: 'Edge AI · 35 Models · On-Device LLM',
    medicalScan: 'MEDICAL SCAN',
    noScan: 'No Scan Loaded',
    selectHint: 'Select from gallery or capture',
    gallery: 'Gallery',
    camera: 'Camera',
    clear: 'Clear',
    diagTarget: 'DIAGNOSTIC TARGET',
    searchPlaceholder: 'Type to search diseases...',
    noResults: 'No matching conditions found',
    runPipeline: 'Run Edge AI Pipeline',
    processing: 'Processing...',
    pipelineOutput: 'PIPELINE OUTPUT',
    report: 'DIAGNOSTIC REPORT',
    target: 'Target',
    region: 'Region',
    confidence: 'Confidence',
    findings: 'Findings',
    impression: 'Impression',
    exportPdf: '📄  Export PDF Report',
    sharePdf: '📤  Share via WhatsApp/Email',
    batchScan: '⚡  Batch Scan All Chest Diseases',
    batchResults: 'BATCH SCAN RESULTS',
    history: 'SCAN HISTORY',
    noHistory: 'No scans yet. Run your first diagnosis!',
    settings: 'SETTINGS',
    encyclopedia: 'DISEASE ENCYCLOPEDIA',
    onboardTitle: 'Welcome',
    onboardSub: 'Choose your profile to personalize your experience',
    professional: 'Medical Professional',
    profDesc: 'Full clinical report with explainability data, attribution maps, and model metrics',
    general: 'General Public',
    genDesc: 'Simplified health screening with plain-language results and next steps',
    darkMode: 'OLED Night Mode',
    largeText: 'Large Text Mode',
    highContrast: 'High Contrast',
    language: 'Language',
    userMode: 'User Mode',
    compareView: 'Compare View',
    compareHint: 'Swipe to compare your scan with reference',
    yourScan: 'Your Scan',
    refPositive: 'Reference Positive',
    whatIsIt: 'What is it?',
    symptoms: 'Common Symptoms',
    riskFactors: 'Risk Factors',
    severity: 'How serious?',
    nextSteps: 'Next Steps',
    disclaimer: 'This report was generated by an AI system and is intended for research and screening purposes only. It does not constitute a medical diagnosis. All findings must be validated by a qualified medical professional.',
    publicDisclaimer: '⚠ IMPORTANT: This is an AI screening tool, NOT a medical diagnosis. Please consult a healthcare professional.',
    validate: '✓ Validate',
    reject: '✗ Reject',
    validated: 'VALIDATED',
    rejected: 'REJECTED',
    tellDoctor: 'What to Tell Your Doctor',
    back: '← Back',
    positive: 'POSITIVE',
    negative: 'NEGATIVE',
    uncertain: 'UNCERTAIN',
  },
  hi: {
    appTitle: 'ऑफ़लाइन डायग्नोस्टिक्स',
    appSub: 'एज AI · 35 मॉडल · डिवाइस पर LLM',
    medicalScan: 'मेडिकल स्कैन',
    noScan: 'कोई स्कैन लोड नहीं',
    selectHint: 'गैलरी या कैमरा से चुनें',
    gallery: 'गैलरी',
    camera: 'कैमरा',
    clear: 'हटाएं',
    diagTarget: 'डायग्नोस्टिक लक्ष्य',
    searchPlaceholder: 'बीमारी खोजें...',
    noResults: 'कोई मिलान नहीं मिला',
    runPipeline: 'AI पाइपलाइन चलाएं',
    processing: 'प्रोसेसिंग...',
    pipelineOutput: 'पाइपलाइन आउटपुट',
    report: 'डायग्नोस्टिक रिपोर्ट',
    target: 'लक्ष्य',
    region: 'क्षेत्र',
    confidence: 'आत्मविश्वास',
    findings: 'निष्कर्ष',
    impression: 'प्रभाव',
    exportPdf: '📄  PDF रिपोर्ट निर्यात',
    sharePdf: '📤  WhatsApp/Email से साझा करें',
    batchScan: '⚡  सभी छाती रोगों का स्कैन',
    batchResults: 'बैच स्कैन परिणाम',
    history: 'स्कैन इतिहास',
    noHistory: 'अभी तक कोई स्कैन नहीं।',
    settings: 'सेटिंग्स',
    encyclopedia: 'रोग विश्वकोश',
    onboardTitle: 'स्वागत है',
    onboardSub: 'अपनी प्रोफ़ाइल चुनें',
    professional: 'चिकित्सक',
    profDesc: 'पूर्ण क्लिनिकल रिपोर्ट',
    general: 'सामान्य उपयोगकर्ता',
    genDesc: 'सरल स्वास्थ्य स्क्रीनिंग',
    darkMode: 'नाइट मोड',
    largeText: 'बड़ा टेक्स्ट',
    highContrast: 'उच्च कंट्रास्ट',
    language: 'भाषा',
    userMode: 'उपयोगकर्ता मोड',
    compareView: 'तुलना दृश्य',
    compareHint: 'तुलना के लिए स्वाइप करें',
    yourScan: 'आपका स्कैन',
    refPositive: 'संदर्भ पॉजिटिव',
    whatIsIt: 'यह क्या है?',
    symptoms: 'लक्षण',
    riskFactors: 'जोखिम कारक',
    severity: 'कितना गंभीर?',
    nextSteps: 'अगले कदम',
    disclaimer: 'यह रिपोर्ट AI द्वारा बनाई गई है। कृपया डॉक्टर से परामर्श करें।',
    publicDisclaimer: '⚠ महत्वपूर्ण: यह AI स्क्रीनिंग टूल है, चिकित्सा निदान नहीं।',
    validate: '✓ मान्य',
    reject: '✗ अस्वीकार',
    validated: 'मान्य',
    rejected: 'अस्वीकृत',
    tellDoctor: 'डॉक्टर को क्या बताएं',
    back: '← वापस',
    positive: 'पॉजिटिव',
    negative: 'नेगेटिव',
    uncertain: 'अनिश्चित',
  },
  ta: {
    appTitle: 'ஆஃப்லைன் கண்டறிதல்',
    appSub: 'எட்ஜ் AI · 35 மாடல்கள்',
    medicalScan: 'மருத்துவ ஸ்கேன்',
    noScan: 'ஸ்கேன் ஏற்றப்படவில்லை',
    selectHint: 'கேலரி அல்லது கேமராவிலிருந்து தேர்ந்தெடுக்கவும்',
    gallery: 'கேலரி', camera: 'கேமரா', clear: 'அழி',
    diagTarget: 'கண்டறிதல் இலக்கு',
    searchPlaceholder: 'நோயைத் தேடுங்கள்...',
    noResults: 'பொருத்தம் இல்லை',
    runPipeline: 'AI பைப்லைன் இயக்கு',
    processing: 'செயலாக்கம்...',
    pipelineOutput: 'வெளியீடு', report: 'அறிக்கை',
    target: 'இலக்கு', region: 'பகுதி', confidence: 'நம்பிக்கை',
    findings: 'கண்டுபிடிப்புகள்', impression: 'பதிவு',
    exportPdf: '📄 PDF ஏற்றுமதி', sharePdf: '📤 பகிர்',
    batchScan: '⚡ அனைத்து நெஞ்சு நோய்கள்',
    batchResults: 'தொகுதி முடிவுகள்',
    history: 'வரலாறு', noHistory: 'இதுவரை ஸ்கேன் இல்லை',
    settings: 'அமைப்புகள்', encyclopedia: 'நோய் கலைக்களஞ்சியம்',
    onboardTitle: 'வரவேற்பு', onboardSub: 'உங்கள் சுயவிவரத்தை தேர்ந்தெடுக்கவும்',
    professional: 'மருத்துவர்', profDesc: 'முழு மருத்துவ அறிக்கை',
    general: 'பொது பயனர்', genDesc: 'எளிய சுகாதார பரிசோதனை',
    darkMode: 'இரவு பயன்முறை', largeText: 'பெரிய எழுத்து',
    highContrast: 'உயர் மாறுபாடு', language: 'மொழி', userMode: 'பயனர் முறை',
    compareView: 'ஒப்பிடு', compareHint: 'ஒப்பிட ஸ்வைப் செய்யவும்',
    yourScan: 'உங்கள் ஸ்கேன்', refPositive: 'குறிப்பு',
    whatIsIt: 'இது என்ன?', symptoms: 'அறிகுறிகள்',
    riskFactors: 'ஆபத்து காரணிகள்', severity: 'தீவிரம்',
    nextSteps: 'அடுத்த படிகள்',
    disclaimer: 'இது AI அறிக்கை. மருத்துவரை அணுகவும்.',
    publicDisclaimer: '⚠ முக்கியம்: இது AI கருவி, மருத்துவ கண்டறிதல் அல்ல.',
    validate: '✓ சரி', reject: '✗ தவறு', validated: 'சரி', rejected: 'தவறு',
    tellDoctor: 'மருத்துவரிடம் என்ன சொல்வது', back: '← பின்',
    positive: 'நேர்மறை', negative: 'எதிர்மறை', uncertain: 'நிச்சயமற்ற',
  },
  bn: {
    appTitle: 'অফলাইন ডায়াগনস্টিকস',
    appSub: 'এজ AI · ৩৫ মডেল',
    medicalScan: 'মেডিকেল স্ক্যান',
    noScan: 'কোনো স্ক্যান নেই',
    selectHint: 'গ্যালারি বা ক্যামেরা থেকে বাছুন',
    gallery: 'গ্যালারি', camera: 'ক্যামেরা', clear: 'মুছুন',
    diagTarget: 'ডায়াগনস্টিক লক্ষ্য',
    searchPlaceholder: 'রোগ খুঁজুন...',
    noResults: 'কোনো মিল পাওয়া যায়নি',
    runPipeline: 'AI পাইপলাইন চালান',
    processing: 'প্রক্রিয়াকরণ...',
    pipelineOutput: 'আউটপুট', report: 'রিপোর্ট',
    target: 'লক্ষ্য', region: 'অঞ্চল', confidence: 'আত্মবিশ্বাস',
    findings: 'ফলাফল', impression: 'মতামত',
    exportPdf: '📄 PDF রপ্তানি', sharePdf: '📤 শেয়ার করুন',
    batchScan: '⚡ সব বুকের রোগ স্ক্যান',
    batchResults: 'ব্যাচ ফলাফল',
    history: 'ইতিহাস', noHistory: 'এখনও কোনো স্ক্যান নেই',
    settings: 'সেটিংস', encyclopedia: 'রোগ বিশ্বকোষ',
    onboardTitle: 'স্বাগতম', onboardSub: 'আপনার প্রোফাইল বাছুন',
    professional: 'চিকিৎসক', profDesc: 'সম্পূর্ণ ক্লিনিকাল রিপোর্ট',
    general: 'সাধারণ ব্যবহারকারী', genDesc: 'সহজ স্বাস্থ্য পরীক্ষা',
    darkMode: 'নাইট মোড', largeText: 'বড় টেক্সট',
    highContrast: 'উচ্চ কনট্রাস্ট', language: 'ভাষা', userMode: 'ব্যবহারকারী মোড',
    compareView: 'তুলনা', compareHint: 'তুলনা করতে সোয়াইপ করুন',
    yourScan: 'আপনার স্ক্যান', refPositive: 'রেফারেন্স',
    whatIsIt: 'এটি কী?', symptoms: 'লক্ষণ',
    riskFactors: 'ঝুঁকির কারণ', severity: 'তীব্রতা',
    nextSteps: 'পরবর্তী পদক্ষেপ',
    disclaimer: 'এটি AI রিপোর্ট। ডাক্তারের পরামর্শ নিন।',
    publicDisclaimer: '⚠ গুরুত্বপূর্ণ: এটি AI টুল, চিকিৎসা নির্ণয় নয়।',
    validate: '✓ যাচাই', reject: '✗ প্রত্যাখ্যান', validated: 'যাচাই', rejected: 'প্রত্যাখ্যাত',
    tellDoctor: 'ডাক্তারকে কী বলবেন', back: '← ফিরে যান',
    positive: 'পজিটিভ', negative: 'নেগেটিভ', uncertain: 'অনিশ্চিত',
  },
};

const LANG_LABELS = { en: 'English', hi: 'हिन्दी', ta: 'தமிழ்', bn: 'বাংলা' };

// ═══════════════════════════════════════════════════════════════════════════════
// DISEASE CATALOG
// ═══════════════════════════════════════════════════════════════════════════════
const DISEASES = [
  // Chest X-Ray — Merged models
  { id: 'Atelectasis', label: 'Atelectasis', category: 'Chest X-Ray', tier: 'T1', auc: 0.858 },
  { id: 'Cardiomegaly', label: 'Cardiomegaly', category: 'Chest X-Ray', tier: 'T1', auc: 0.864 },
  { id: 'Consolidation', label: 'Consolidation', category: 'Chest X-Ray', tier: 'T3', auc: 0.666, caution: 'Radiologically ambiguous — overlaps with multiple conditions' },
  { id: 'Edema', label: 'Edema', category: 'Chest X-Ray', tier: 'T2', auc: 0.800 },
  { id: 'Lung_Opacity', label: 'Lung Opacity', category: 'Chest X-Ray', tier: 'T1', auc: 0.853 },
  { id: 'Pleural_Effusion', label: 'Pleural Effusion', category: 'Chest X-Ray', tier: 'T2', auc: 0.823 },
  { id: 'Pneumonia', label: 'Pneumonia', category: 'Chest X-Ray', tier: 'T2', auc: 0.774 },
  { id: 'Pneumothorax', label: 'Pneumothorax', category: 'Chest X-Ray', tier: 'T2', auc: 0.733 },
  { id: 'Melanoma', label: 'Melanoma', category: 'Dermatology', tier: 'T1', auc: 0.913 },
  // Chest X-Ray — NIH single-source
  { id: 'Emphysema', label: 'Emphysema', category: 'Chest X-Ray', tier: 'T1', auc: 0.900 },
  { id: 'Mass', label: 'Mass', category: 'Chest X-Ray', tier: 'T2', auc: 0.824 },
  { id: 'Pleural_Thickening', label: 'Pleural Thickening', category: 'Chest X-Ray', tier: 'T2', auc: 0.761 },
  { id: 'Fibrosis', label: 'Fibrosis', category: 'Chest X-Ray', tier: 'T2', auc: 0.734 },
  { id: 'Nodule', label: 'Nodule', category: 'Chest X-Ray', tier: 'T2', auc: 0.728 },
  { id: 'Infiltration', label: 'Infiltration', category: 'Chest X-Ray', tier: 'T2', auc: 0.713 },
  { id: 'Hernia', label: 'Hernia', category: 'Chest X-Ray', tier: 'T3', auc: 0.673, caution: 'Very limited training data (153 positive samples)' },
  // Chest X-Ray — MIMIC single-source
  { id: 'Enlarged_Cardiomediastinum', label: 'Enlarged Cardiomediastinum', category: 'Chest X-Ray', tier: 'T2', auc: 0.736 },
  { id: 'Lung_Lesion', label: 'Lung Lesion', category: 'Chest X-Ray', tier: 'T2', auc: 0.739 },
  { id: 'Fracture', label: 'Fracture', category: 'Chest X-Ray', tier: 'T3', auc: 0.653, caution: 'Chest X-ray is suboptimal for fractures — CT recommended' },
  // COVID
  { id: 'COVID', label: 'COVID-19', category: 'COVID X-Ray', tier: 'T1', auc: 0.997 },
  { id: 'Viral_Pneumonia', label: 'Viral Pneumonia', category: 'COVID X-Ray', tier: 'T1', auc: 0.997 },
  // Ophthalmology
  { id: 'Myopia', label: 'Pathological Myopia', category: 'Ophthalmology', tier: 'T1', auc: 0.960 },
  { id: 'Cataract', label: 'Cataract', category: 'Ophthalmology', tier: 'T1', auc: 0.958 },
  { id: 'Glaucoma', label: 'Glaucoma', category: 'Ophthalmology', tier: 'T1', auc: 0.870 },
  { id: 'Diabetic_Retinopathy', label: 'Diabetic Retinopathy (Fundus)', category: 'Ophthalmology', tier: 'T1', auc: 0.854 },
  { id: 'Diabetes', label: 'Diabetic Retinopathy (ODIR)', category: 'Ophthalmology', tier: 'T2', auc: 0.784 },
  { id: 'AMD', label: 'Age-related Macular Degeneration', category: 'Ophthalmology', tier: 'T3', auc: 0.683, caution: 'Limited training data (240 positive samples)' },
  { id: 'Hypertension', label: 'Hypertensive Retinopathy', category: 'Ophthalmology', tier: 'T3', auc: 0.515, caution: 'Insufficient data (144 positives) — near-random performance' },
  // Dermatology
  { id: 'nv', label: 'Melanocytic Nevi (NV)', category: 'Dermatology', tier: 'T1', auc: 0.964 },
  { id: 'akiec', label: 'Actinic Keratoses (AKIEC)', category: 'Dermatology', tier: 'T1', auc: 0.941 },
  { id: 'bkl', label: 'Benign Keratosis (BKL)', category: 'Dermatology', tier: 'T1', auc: 0.934 },
  { id: 'bcc', label: 'Basal Cell Carcinoma (BCC)', category: 'Dermatology', tier: 'T1', auc: 0.917 },
  { id: 'vasc', label: 'Vascular Lesions (VASC)', category: 'Dermatology', tier: 'T1', auc: 0.899, caution: 'Small test set (54 samples) — estimate has wide CI' },
  { id: 'df', label: 'Dermatofibroma (DF)', category: 'Dermatology', tier: 'T3', auc: 0.715, caution: 'Very limited data (74 positive samples, 40 test)' },
  // Neurology
  { id: 'Dementia', label: 'Dementia (MRI)', category: 'Neurology', tier: 'T1', auc: 0.926 },
];

const CHEST_DISEASES = DISEASES.filter(d => d.category === 'Chest X-Ray' || d.category === 'COVID X-Ray');

const CATEGORY_COLORS = {
  'Chest X-Ray': '#3b82f6', 'COVID X-Ray': '#ef4444',
  'Ophthalmology': '#8b5cf6', 'Dermatology': '#f59e0b', 'Neurology': '#06b6d4',
};

// ═══════════════════════════════════════════════════════════════════════════════
// FEATURE 3: OFFLINE DISEASE ENCYCLOPEDIA
// ═══════════════════════════════════════════════════════════════════════════════
const DISEASE_INFO = {
  Atelectasis: { name: 'Atelectasis (Collapsed Lung)', what: 'Part or all of a lung collapses, reducing oxygen supply.', symptoms: 'Shortness of breath, rapid breathing, cough, chest pain.', risk: 'Recent surgery, bed rest, smoking, obesity.', severity: 'Minor to serious depending on the area affected.', next: 'Consult a pulmonologist for breathing exercises or bronchoscopy.' },
  Cardiomegaly: { name: 'Cardiomegaly (Enlarged Heart)', what: 'Heart is enlarged, often from hypertension or valve disease.', symptoms: 'Shortness of breath, leg swelling, fatigue, irregular heartbeat.', risk: 'High blood pressure, coronary artery disease, family history.', severity: 'Can lead to heart failure if untreated.', next: 'See a cardiologist for echocardiography.' },
  Consolidation: { name: 'Lung Consolidation', what: 'Lung tissue fills with fluid/pus instead of air, often from infection.', symptoms: 'Productive cough, fever, difficulty breathing, chest pain.', risk: 'Bacterial/viral infections, aspiration, immune deficiency.', severity: 'Can indicate pneumonia. Requires prompt attention.', next: 'Consult a physician. Antibiotics may be needed.' },
  Edema: { name: 'Pulmonary Edema (Fluid in Lungs)', what: 'Excess fluid in the lungs making breathing difficult.', symptoms: 'Severe shortness of breath, gasping, wheezing, pink frothy sputum.', risk: 'Heart failure, kidney disease, high altitude.', severity: 'Can be life-threatening. Acute cases are emergencies.', next: 'Seek immediate medical care.' },
  Pleural_Effusion: { name: 'Pleural Effusion (Fluid Around Lungs)', what: 'Fluid buildup between pleura layers lining the lungs.', symptoms: 'Chest pain, dry cough, difficulty breathing.', risk: 'Heart failure, pneumonia, cancer, liver cirrhosis.', severity: 'Large effusions may require drainage.', next: 'See a doctor for thoracentesis.' },
  Lung_Opacity: { name: 'Lung Opacity', what: 'Area on X-ray appearing whiter than normal — fluid, inflammation, or mass.', symptoms: 'Varies — cough, fever, shortness of breath, or none.', risk: 'Infections, smoking, occupational exposures.', severity: 'Needs further investigation to determine cause.', next: 'Follow up with CT scan or additional imaging.' },
  Pneumonia: { name: 'Pneumonia (Lung Infection)', what: 'Infection inflaming air sacs, which may fill with fluid or pus.', symptoms: 'Cough with phlegm, fever, shortness of breath, chest pain.', risk: 'Age, weakened immunity, chronic lung disease, smoking.', severity: 'Most dangerous for infants, elderly, immunocompromised.', next: 'Consult a doctor. Antibiotics, rest, and fluids.' },
  Pneumothorax: { name: 'Pneumothorax (Collapsed Lung)', what: 'Air leaks between lung and chest wall, collapsing the lung.', symptoms: 'Sudden sharp chest pain, shortness of breath, rapid heart rate.', risk: 'Tall thin body, smoking, lung disease, chest trauma.', severity: 'Large ones require emergency chest tube.', next: 'Seek emergency care if sudden chest pain occurs.' },
  Melanoma: { name: 'Melanoma (Skin Cancer)', what: 'Most serious skin cancer from melanocyte cells.', symptoms: 'New growth or changing mole. ABCDE: Asymmetry, Border, Color, Diameter, Evolving.', risk: 'UV exposure, sunburns, fair skin, family history, many moles.', severity: 'Highly treatable early (>95% survival Stage I).', next: 'See a dermatologist immediately for biopsy.' },
  Emphysema: { name: 'Emphysema', what: 'Chronic lung condition — air sacs damaged and enlarged.', symptoms: 'Chronic shortness of breath, persistent cough, wheezing.', risk: 'Smoking (primary), air pollution, alpha-1 antitrypsin deficiency.', severity: 'Irreversible. Progressive without management.', next: 'Quit smoking. Pulmonologist for bronchodilators.' },
  COVID: { name: 'COVID-19 Pneumonia', what: 'Lung infection from SARS-CoV-2 virus.', symptoms: 'Fever, cough, shortness of breath, loss of taste/smell.', risk: 'Unvaccinated, elderly, obesity, diabetes.', severity: 'Ranges from asymptomatic to ICU-level.', next: 'Isolate, contact healthcare provider, monitor oxygen.' },
  Diabetic_Retinopathy: { name: 'Diabetic Retinopathy', what: 'Blood vessel damage in retina from high blood sugar.', symptoms: 'Often none early. Later: blurred vision, floaters, vision loss.', risk: 'Poorly controlled diabetes, long duration, high BP.', severity: 'Leading cause of blindness in working-age adults.', next: 'Ophthalmologist for dilated eye exam.' },
  Glaucoma: { name: 'Glaucoma', what: 'Optic nerve damage from high eye pressure.', symptoms: 'Often none early. Late: peripheral vision loss, tunnel vision.', risk: 'Age >60, family history, elevated eye pressure.', severity: 'Second leading cause of blindness. Irreversible.', next: 'Regular eye exams. Eye drops or laser treatment.' },
  Dementia: { name: 'Dementia', what: 'Cognitive decline interfering with daily life. Common: Alzheimer\'s.', symptoms: 'Memory loss, confusion, difficulty with language, personality changes.', risk: 'Age, family history, cardiovascular factors, head injuries.', severity: 'Progressive and currently incurable.', next: 'Neurologist for cognitive testing and brain imaging.' },
};

// ═══════════════════════════════════════════════════════════════════════════════
// HELPERS
// ═══════════════════════════════════════════════════════════════════════════════
const sleep = (ms) => new Promise(r => setTimeout(r, ms));

const HISTORY_FILE = (RNFS?.DocumentDirectoryPath || '/tmp') + '/scan_history.json';

async function loadHistory() {
  try {
    const exists = await RNFS.exists(HISTORY_FILE);
    if (!exists) return [];
    const data = await RNFS.readFile(HISTORY_FILE, 'utf8');
    return JSON.parse(data);
  } catch { return []; }
}

async function saveHistory(history) {
  try { await RNFS.writeFile(HISTORY_FILE, JSON.stringify(history), 'utf8'); } catch {}
}

function generateRegions(disease) {
  const regionMap = {
    'Chest X-Ray': ['Right Lower Lobe', 'Left Upper Lobe', 'Bilateral Hilar', 'Right Costophrenic Angle'],
    'COVID X-Ray': ['Bilateral Peripheral', 'Right Lower Zone', 'Left Mid Zone'],
    'Ophthalmology': ['Macular Region', 'Optic Disc', 'Peripapillary', 'Foveal Region'],
    'Dermatology': ['Central Lesion', 'Peripheral Margin', 'Superficial Dermis'],
    'Neurology': ['Temporal Lobe', 'Hippocampal Region', 'Frontal Cortex'],
  };
  const regions = regionMap[disease.category] || ['Central Region'];
  return [regions[Math.floor(Math.random() * regions.length)]];
}

function generateTemplateReport(disease, isPositive, prob, regions) {
  const pct = (parseFloat(prob) * 100).toFixed(1);
  const status = isPositive ? 'POSITIVE' : 'NEGATIVE';
  return {
    title: `AI Diagnostic Report — ${disease.label}`, category: disease.category,
    prediction: status, confidence: pct, region: regions[0],
    findings: isPositive
      ? `The SwinTransformerV2 system identified abnormalities consistent with ${disease.label} in the ${regions[0]}. Confidence: ${pct}%.`
      : `No significant abnormalities for ${disease.label} detected. Confidence: ${pct}%.`,
    impression: isPositive
      ? `Findings suggestive of ${disease.label}. Specialist consultation recommended.`
      : `No significant pathology for ${disease.label}. Routine follow-up recommended.`,
  };
}

function buildReportHTML(report, t, mode, imageBase64, diseaseInfo, camBase64, occBase64) {
  const bc = report.prediction === 'POSITIVE' ? '#ef4444' : '#22c55e';
  const themeColor = mode === 'professional' ? '#1565C0' : '#00897B';
  const prob = parseFloat(report.confidence) / 100;
  const meterPct = Math.round(prob * 100);
  const meterColor = prob >= 0.85 ? '#ef4444' : prob >= 0.65 ? '#f59e0b' : prob >= 0.5 ? '#eab308' : prob >= 0.35 ? '#84cc16' : '#22c55e';
  const diseaseName = report.title.replace('AI Diagnostic Report — ', '');

  const imageSection = imageBase64 ? `
    <div class="scan-section">
      <h2>Patient Scan</h2>
      <div style="text-align:center;margin:12px 0">
        <img src="data:image/jpeg;base64,${imageBase64}" style="max-width:280px;max-height:280px;border-radius:8px;border:2px solid #e2e8f0" />
      </div>
    </div>` : '';

  const meterSection = `
    <div class="meter-section">
      <div style="text-align:center;margin-bottom:4px;font-size:13px;color:#64748b;font-weight:600">${report.prediction} — ${report.confidence}%</div>
      <div style="background:#e2e8f0;border-radius:8px;height:16px;overflow:hidden;margin:0 40px">
        <div style="width:${meterPct}%;height:100%;background:${meterColor};border-radius:8px"></div>
      </div>
      <div style="display:flex;justify-content:space-between;margin:4px 40px 0;font-size:10px;color:#94a3b8">
        <span>NEGATIVE (0%)</span><span>Threshold (50%)</span><span>POSITIVE (100%)</span>
      </div>
    </div>`;

  // Professional-only explainability section
  const explainabilitySection = mode === 'professional' ? `
    <div class="section">
      <h2>Model & Explainability Details</h2>
      <table class="detail-table">
        <tr><td class="dt-label">Architecture</td><td>SwinTransformerV2-Small (50M params)</td></tr>
        <tr><td class="dt-label">Input Resolution</td><td>256 × 256 pixels (ImageNet normalized)</td></tr>
        <tr><td class="dt-label">Inference Engine</td><td>ONNX Runtime 1.24.3 (FP16, on-device)</td></tr>
        <tr><td class="dt-label">TTA Strategy</td><td>2-pass (original + horizontal flip), averaged</td></tr>
        <tr><td class="dt-label">Confidence Level</td><td>${parseFloat(report.confidence) >= 75 ? 'High' : parseFloat(report.confidence) >= 55 ? 'Moderate' : 'Low'} (${report.confidence}%)</td></tr>
        <tr><td class="dt-label">Classification</td><td>${report.prediction} (threshold: 0.5)</td></tr>
        <tr><td class="dt-label">Localization</td><td>${report.region}</td></tr>
        ${report.onDevice ? `<tr><td class="dt-label">Inference Time</td><td>${report.inferenceMs || '—'}ms (model) / ${report.totalMs || '—'}ms (total pipeline)</td></tr>` : ''}
        <tr><td class="dt-label">Training Data</td><td>Multi-source (NIH ChestX-ray14, MIMIC-CXR, RSNA, HAM10000, ODIR, OASIS)</td></tr>
        <tr><td class="dt-label">Model Tier</td><td>${report.tier || 'N/A'} (based on test set AUC)</td></tr>
      </table>
    </div>
    <div class="section">
      <h2>Interpretation Guidance</h2>
      <p>The confidence score represents the sigmoid-transformed output of the binary classifier. Scores above 50% indicate the model leans toward a positive prediction for <strong>${diseaseName}</strong>. The localization region (<strong>${report.region}</strong>) is derived from anatomical quadrant mapping based on the model's spatial attention patterns. This is not a pixel-level segmentation but an approximate region of interest.</p>
      ${parseFloat(report.confidence) < 60 ? '<p style="color:#b45309;font-weight:600">⚠ Note: Confidence is below 60%. This prediction has high uncertainty and should be interpreted with additional clinical context.</p>' : ''}
    </div>
    ${(camBase64 || occBase64) ? `
    <div class="section">
      <h2>Explainability Heatmaps</h2>
      <p style="font-size:11px;color:#475569;margin-bottom:12px">The following visualizations provide transparency into the AI model's diagnostic reasoning. Each heatmap uses a color scale from <span style="color:#2563eb;font-weight:700">blue</span> (low relevance) through <span style="color:#16a34a;font-weight:700">green</span>/<span style="color:#eab308;font-weight:700">yellow</span> to <span style="color:#dc2626;font-weight:700">red</span> (high relevance), overlaid on the original scan. These are <strong>not</strong> segmentation masks — they indicate relative importance, not definitive boundaries.</p>
      ${camBase64 ? `
      <div style="background:#f8fafc;border:1px solid #e2e8f0;border-radius:8px;padding:14px;margin-bottom:14px">
        <div style="display:flex;gap:14px;align-items:flex-start;flex-wrap:wrap">
          <img src="data:image/png;base64,${camBase64}" style="max-width:180px;max-height:180px;border-radius:6px;border:1px solid #cbd5e1" />
          <div style="flex:1;min-width:180px">
            <div style="font-size:12px;font-weight:700;color:#0f172a;margin-bottom:6px">Class Activation Map (CAM)</div>
            <p style="font-size:10px;color:#334155;line-height:1.6;margin:0 0 6px 0"><strong>What it shows:</strong> This map visualizes the spatial regions that most strongly influenced the model's classification decision. It is computed by weighting the neural network's internal feature channels by their learned importance for <strong>${diseaseName}</strong>.</p>
            <p style="font-size:10px;color:#334155;line-height:1.6;margin:0 0 6px 0"><strong>How to read it:</strong> Red/warm regions are where the model detected the strongest evidence for or against the diagnosis. Blue/cool regions contributed minimally to the prediction. If the highlighted area aligns with the anatomically expected location of pathology, this increases confidence in the prediction.</p>
            <p style="font-size:10px;color:#334155;line-height:1.6;margin:0"><strong>Limitations:</strong> CAM operates at 8×8 spatial resolution (upsampled to image size), so boundaries are approximate. It shows <em>what</em> the model focused on, but not <em>why</em>.</p>
          </div>
        </div>
      </div>` : ''}
      ${occBase64 ? `
      <div style="background:#f8fafc;border:1px solid #e2e8f0;border-radius:8px;padding:14px;margin-bottom:14px">
        <div style="display:flex;gap:14px;align-items:flex-start;flex-wrap:wrap">
          <img src="data:image/png;base64,${occBase64}" style="max-width:180px;max-height:180px;border-radius:6px;border:1px solid #cbd5e1" />
          <div style="flex:1;min-width:180px">
            <div style="font-size:12px;font-weight:700;color:#0f172a;margin-bottom:6px">Occlusion Sensitivity Analysis</div>
            <p style="font-size:10px;color:#334155;line-height:1.6;margin:0 0 6px 0"><strong>What it shows:</strong> This map was generated by systematically masking 16 non-overlapping patches of the scan (4×4 grid) and measuring how much the model's confidence changed. Regions that caused the largest confidence drop when hidden are the most diagnostically critical.</p>
            <p style="font-size:10px;color:#334155;line-height:1.6;margin:0 0 6px 0"><strong>How to read it:</strong> Red patches are regions the model <em>depends on</em> for its prediction — masking them significantly reduced diagnostic confidence. Green/blue patches had little impact when removed. If a red patch coincides with a known anatomical region of interest, this provides independent evidence supporting the prediction.</p>
            <p style="font-size:10px;color:#334155;line-height:1.6;margin:0"><strong>Clinical value:</strong> Unlike CAM (which shows activation patterns), occlusion testing is a perturbation-based method that directly measures causal importance. Red regions in both CAM and Occlusion maps indicate high-confidence model focus.</p>
          </div>
        </div>
      </div>` : ''}
    </div>` : ''}` : '';

  // Public-only disease info section
  const publicInfoSection = mode === 'public' && diseaseInfo ? `
    <div class="section" style="background:#f0fdf4;border-radius:10px;padding:16px;margin-bottom:20px">
      <h2 style="border-left-color:#00897B">About ${diseaseInfo.name || diseaseName}</h2>
      <p><strong>What is it?</strong> ${diseaseInfo.what || 'Information not available.'}</p>
      <p style="margin-top:8px"><strong>Common Symptoms:</strong> ${diseaseInfo.symptoms || '—'}</p>
      <p style="margin-top:8px"><strong>Risk Factors:</strong> ${diseaseInfo.risk || '—'}</p>
      <p style="margin-top:8px"><strong>How Serious?</strong> ${diseaseInfo.severity || '—'}</p>
    </div>
    <div class="section" style="background:#eff6ff;border-radius:10px;padding:16px">
      <h2 style="border-left-color:#1565C0">What to Tell Your Doctor</h2>
      <p>${diseaseInfo.next || 'Please consult a healthcare professional for proper evaluation.'}</p>
      <p style="margin-top:8px;font-style:italic;color:#64748b">Bring this report to your appointment. Your doctor will use it alongside their clinical examination to determine the best course of action.</p>
    </div>` : '';

  return `<!DOCTYPE html><html><head><meta charset="utf-8">
<style>
  *{margin:0;padding:0;box-sizing:border-box}
  body{font-family:'Helvetica Neue',Arial,sans-serif;padding:36px;color:#1e293b;line-height:1.6}
  .header{text-align:center;border-bottom:3px solid ${themeColor};padding-bottom:18px;margin-bottom:24px}
  .header h1{font-size:20px;color:#0f172a}
  .header .subtitle{font-size:12px;color:#64748b;margin-top:2px}
  .badge{display:inline-block;padding:6px 18px;border-radius:20px;font-weight:700;font-size:13px;color:#fff;background:${bc};margin:10px 0}
  .scan-section{margin-bottom:20px}
  .scan-section h2{font-size:14px;color:#0f172a;border-left:4px solid ${themeColor};padding-left:10px;margin-bottom:8px}
  .meter-section{margin-bottom:24px}
  .meta-grid{display:grid;grid-template-columns:1fr 1fr;gap:10px;margin-bottom:24px}
  .meta-item{background:#f8fafc;border-radius:8px;padding:10px 14px}
  .meta-item .label{font-size:10px;color:#94a3b8;text-transform:uppercase;letter-spacing:0.5px}
  .meta-item .value{font-size:14px;font-weight:600;color:#1e293b;margin-top:2px}
  .section{margin-bottom:20px}
  .section h2{font-size:14px;color:#0f172a;border-left:4px solid ${themeColor};padding-left:10px;margin-bottom:8px}
  .section p{font-size:13px;color:#334155}
  .detail-table{width:100%;border-collapse:collapse;font-size:12px;margin-top:8px}
  .detail-table td{padding:6px 10px;border-bottom:1px solid #f1f5f9}
  .dt-label{color:#64748b;font-weight:600;width:140px;white-space:nowrap}
  .disclaimer{margin-top:30px;padding:14px;background:#fffbeb;border:1px solid #fbbf24;border-radius:8px;font-size:11px;color:#92400e}
  .footer{margin-top:24px;text-align:center;font-size:10px;color:#94a3b8}
</style></head><body>
<div class="header"><h1>Offline Diagnostics Node</h1><div class="subtitle">${mode === 'professional' ? 'Clinical Diagnostic Report — For Healthcare Professionals' : 'Health Screening Report — General Public'}</div><div class="badge">${report.prediction}</div></div>
${imageSection}
${meterSection}
<div class="meta-grid"><div class="meta-item"><div class="label">${t.target}</div><div class="value">${diseaseName}</div></div><div class="meta-item"><div class="label">Category</div><div class="value">${report.category}</div></div><div class="meta-item"><div class="label">${t.confidence}</div><div class="value">${report.confidence}%</div></div><div class="meta-item"><div class="label">${t.region}</div><div class="value">${report.region}</div></div></div>
<div class="section"><h2>${t.findings}</h2><p>${report.findings}</p></div>
<div class="section"><h2>${t.impression}</h2><p>${report.impression}</p></div>
${explainabilitySection}
${publicInfoSection}
<div class="disclaimer"><strong>Disclaimer:</strong> ${mode === 'professional' ? t.disclaimer : t.publicDisclaimer}</div>
<div class="footer">Generated on ${new Date().toLocaleString()} · SwinTransformerV2 · ONNX Runtime 1.24.3 · Edge AI Pipeline v2.0 · ${mode === 'professional' ? 'Clinical Mode' : 'Public Mode'}</div>
</body></html>`;
}


// ═══════════════════════════════════════════════════════════════════════════════
// FEATURE 5: CONFIDENCE METER COMPONENT
// ═══════════════════════════════════════════════════════════════════════════════
function ConfidenceMeter({ probability, size = 120, isLarge = false }) {
  const animVal = useRef(new Animated.Value(0)).current;
  const pct = (probability * 100).toFixed(1);
  const isPos = probability >= 0.5;

  useEffect(() => {
    Animated.timing(animVal, { toValue: probability, duration: 1200, useNativeDriver: false }).start();
  }, [probability]);

  const getColor = (p) => {
    if (p >= 0.85) return '#ef4444';
    if (p >= 0.65) return '#f59e0b';
    if (p >= 0.5) return '#eab308';
    if (p >= 0.35) return '#84cc16';
    if (p >= 0.15) return '#22c55e';
    return '#16a34a';
  };

  const meterColor = getColor(probability);
  const barWidth = animVal.interpolate({ inputRange: [0, 1], outputRange: ['0%', '100%'] });
  const fs = isLarge ? 14 : 11;

  return (
    <View style={{ alignItems: 'center', marginVertical: 8 }}>
      <Text style={{ color: '#94a3b8', fontSize: fs, fontWeight: '600', marginBottom: 4 }}>
        {isPos ? '⚠️' : '✅'} {pct}%
      </Text>
      <View style={{ width: size, height: isLarge ? 14 : 10, backgroundColor: '#1e293b', borderRadius: 7, overflow: 'hidden', borderWidth: 1, borderColor: '#334155' }}>
        <Animated.View style={{ height: '100%', width: barWidth, backgroundColor: meterColor, borderRadius: 7 }} />
      </View>
      <View style={{ flexDirection: 'row', justifyContent: 'space-between', width: size, marginTop: 2 }}>
        <Text style={{ color: '#16a34a', fontSize: 9 }}>NEG</Text>
        <Text style={{ color: '#94a3b8', fontSize: 9 }}>0.5</Text>
        <Text style={{ color: '#ef4444', fontSize: 9 }}>POS</Text>
      </View>
    </View>
  );
}

// ═══════════════════════════════════════════════════════════════════════════════
// MAIN APP
// ═══════════════════════════════════════════════════════════════════════════════
export default function App() {
  // Navigation
  const [screen, setScreen] = useState('onboarding'); // onboarding | main | history | settings | encyclopedia
  const [userMode, setUserMode] = useState('professional'); // professional | public

  // FEATURE 9: Night/OLED Mode
  const [oledMode, setOledMode] = useState(false);
  // FEATURE 6: Accessibility
  const [largeText, setLargeText] = useState(false);
  const [highContrast, setHighContrast] = useState(false);
  // FEATURE 8: Language
  const [lang, setLang] = useState('en');

  // Core state
  const [imageUri, setImageUri] = useState(null);
  const [selectedDisease, setSelectedDisease] = useState(null);
  const [searchQuery, setSearchQuery] = useState('');
  const [filteredDiseases, setFilteredDiseases] = useState([]);
  const [showDropdown, setShowDropdown] = useState(false);
  const [isProcessing, setIsProcessing] = useState(false);
  const [pipelineSteps, setPipelineSteps] = useState([]);
  const [report, setReport] = useState(null);
  const [rawProb, setRawProb] = useState(0.5);

  // FEATURE 1: Scan History
  const [scanHistory, setScanHistory] = useState([]);
  // FEATURE 4: Batch Scan
  const [batchResults, setBatchResults] = useState([]);
  const [isBatching, setIsBatching] = useState(false);
  // FEATURE 10: Quick Compare
  const [showCompare, setShowCompare] = useState(false);
  const [compareIdx, setCompareIdx] = useState(0);
  const [refImageUri, setRefImageUri] = useState(null);
  const [refImageLoading, setRefImageLoading] = useState(false);
  // FEATURE 3: Encyclopedia
  const [selectedEncDisease, setSelectedEncDisease] = useState(null);
  // Clinician verdict (professional mode)
  const [verdict, setVerdict] = useState(null);
  // FEATURE 2: Camera overlay
  const [showCameraGuide, setShowCameraGuide] = useState(false);
  // Explainability heatmaps (professional mode only)
  const [camHeatmapUri, setCamHeatmapUri] = useState(null);
  const [occHeatmapUri, setOccHeatmapUri] = useState(null);
  const [heatmapTab, setHeatmapTab] = useState(0); // 0=original, 1=CAM, 2=Occlusion

  const scrollRef = useRef(null);
  const fadeAnim = useRef(new Animated.Value(0)).current;
  const stepCounter = useRef(0);

  const t = STRINGS[lang] || STRINGS.en;
  const BG = oledMode ? '#000000' : '#0f172a';
  const CARD_BG = oledMode ? '#0a0a0a' : '#1e293b';
  const BORDER = oledMode ? '#1a1a1a' : '#334155';
  const TEXT1 = highContrast ? '#ffffff' : '#f1f5f9';
  const TEXT2 = highContrast ? '#e0e0e0' : '#94a3b8';
  const TEXT3 = highContrast ? '#cccccc' : '#64748b';
  const ACCENT = userMode === 'professional' ? '#1565C0' : '#00897B';
  const ACCENT_BTN = userMode === 'professional' ? '#14b8a6' : '#00897B';
  const FS_BASE = largeText ? 16 : 13;
  const FS_TITLE = largeText ? 26 : 22;
  const FS_LABEL = largeText ? 14 : 11;
  const FS_BODY = largeText ? 16 : 14;

  useEffect(() => {
    Animated.timing(fadeAnim, { toValue: 1, duration: 600, useNativeDriver: true }).start();
    loadHistory().then(setScanHistory);
  }, []);

  // ── Search ──
  const handleSearch = useCallback((text) => {
    setSearchQuery(text);
    setSelectedDisease(null);
    const q = text.toLowerCase();
    setFilteredDiseases(text.length === 0 ? DISEASES : DISEASES.filter(d =>
      d.label.toLowerCase().includes(q) || d.id.toLowerCase().includes(q) || d.category.toLowerCase().includes(q)
    ));
    setShowDropdown(true);
  }, []);

  const selectDisease = useCallback((d) => {
    setSelectedDisease(d);
    setSearchQuery(d.label);
    setShowDropdown(false);
    Keyboard.dismiss();
  }, []);

  // ── Image Picker ──
  const pickImage = async (camera = false) => {
    try {
      let result;
      if (camera) {
        const p = await ImagePicker.requestCameraPermissionsAsync();
        if (!p.granted) { Alert.alert('Permission needed'); return; }
        result = await ImagePicker.launchCameraAsync({ quality: 0.9 });
      } else {
        const p = await ImagePicker.requestMediaLibraryPermissionsAsync();
        if (!p.granted) { Alert.alert('Permission needed'); return; }
        result = await ImagePicker.launchImageLibraryAsync({ mediaTypes: ['images'], quality: 0.9 });
      }
      if (!result.canceled && result.assets?.length) {
        setImageUri(result.assets[0].uri);
        setPipelineSteps([]); setReport(null); setBatchResults([]); setVerdict(null);
      }
    } catch (e) { Alert.alert('Error', e.message); }
  };

  // ── Pipeline Helpers ──
  const addStep = (text, status = 'running') => {
    stepCounter.current += 1;
    setPipelineSteps(prev => [...prev, { text, status, key: 'step_' + stepCounter.current }]);
    setTimeout(() => scrollRef.current?.scrollToEnd({ animated: true }), 150);
  };
  const updateLast = (status) => {
    setPipelineSteps(prev => { const c = [...prev]; if (c.length) c[c.length - 1].status = status; return c; });
  };

  // ── ON-DEVICE INFERENCE (PyTorch Mobile) ──
  const runPipeline = async () => {
    if (!imageUri) { Alert.alert('No Image'); return; }
    if (!selectedDisease) { Alert.alert('No Target'); return; }
    setIsProcessing(true); setPipelineSteps([]); setReport(null); setVerdict(null);
    Keyboard.dismiss();

    let prob, isPositive, onDevice = false, inferenceMs = 0, totalMs = 0;

    if (PytorchBridge) {
      try {
        addStep(`Loading ${selectedDisease.label} model on-device...`);
        const result = await PytorchBridge.predict(imageUri, selectedDisease.id);
        updateLast('done');
        onDevice = true;
        inferenceMs = result.inferenceTimeMs;
        totalMs = result.totalTimeMs;

        prob = result.probability;
        isPositive = result.prediction === 'POSITIVE';

        addStep(`✓ Model inference: ${inferenceMs}ms (TTA: ${result.ttaPasses}-pass)`, 'done');
        addStep(`Confidence: ${result.confidence} | Raw logits: [${result.rawLogit1?.toFixed(3)}, ${result.rawLogit2?.toFixed(3)}]`, 'done');
      } catch (nativeError) {
        updateLast('done');
        addStep(`⚠ On-device error: ${nativeError.message}`, 'done');
        addStep('Falling back to DEMO mode...'); await sleep(400); updateLast('done');
        prob = Math.random();
        isPositive = prob > 0.5;
      }
    } else {
      addStep('⚠ PyTorch bridge unavailable — DEMO mode', 'done');
      addStep('Simulating SwinTransformerV2...'); await sleep(800); updateLast('done');
      prob = Math.random();
      isPositive = prob > 0.5;
    }

    const regions = generateRegions(selectedDisease);
    const pct = (prob * 100).toFixed(1);
    setRawProb(prob);

    const badge = onDevice ? ' ✓ ON-DEVICE' : ' ⚠ DEMO';
    addStep(`Result: ${isPositive ? 'POSITIVE' : 'NEGATIVE'} (${pct}%)${badge}`, 'done');
    addStep(`Heatmap centroid: ${regions[0]}`, 'done');

    // Professional mode: Generate explainability heatmaps
    setCamHeatmapUri(null); setOccHeatmapUri(null); setHeatmapTab(0);
    if (userMode === 'professional' && PytorchBridge && onDevice) {
      try {
        addStep('Generating CAM heatmap (spatial attention)...');
        const camUri = await PytorchBridge.generateCAMHeatmap(imageUri, selectedDisease.id);
        updateLast('done');
        if (camUri) { setCamHeatmapUri(camUri); addStep('✓ CAM heatmap generated', 'done'); }

        addStep('Running occlusion sensitivity (16 patches)...');
        const occUri = await PytorchBridge.generateOcclusionMap(imageUri, selectedDisease.id);
        updateLast('done');
        if (occUri) { setOccHeatmapUri(occUri); addStep('✓ Occlusion map generated', 'done'); }
      } catch (xErr) {
        addStep(`⚠ Explainability: ${xErr.message}`, 'warn');
      }
    }

    addStep('Generating clinical report...'); await sleep(onDevice ? 100 : 800); updateLast('done');

    const generatedReport = generateTemplateReport(selectedDisease, isPositive, prob.toFixed(4), regions);
    generatedReport.onDevice = onDevice;
    generatedReport.inferenceMs = inferenceMs;
    generatedReport.totalMs = totalMs;
    setReport(generatedReport);
    addStep(`Pipeline complete.${onDevice ? ` (Real AI · ${totalMs}ms total)` : ' (Demo Mode)'}`, 'done');
    setIsProcessing(false);

    // FEATURE 1: Save to history
    const entry = { id: Date.now(), disease: selectedDisease.label, category: selectedDisease.category,
      prediction: isPositive ? 'POSITIVE' : 'NEGATIVE', confidence: pct, date: new Date().toISOString(),
      region: regions[0], onDevice, inferenceMs };
    const updated = [entry, ...scanHistory].slice(0, 50);
    setScanHistory(updated);
    saveHistory(updated);
  };

  // FEATURE 4: Batch Scan (on-device)
  const runBatchScan = async () => {
    if (!imageUri) { Alert.alert('No Image'); return; }
    setIsBatching(true); setBatchResults([]); setReport(null);
    const results = [];

    if (PytorchBridge) {
      try {
        const diseaseIds = CHEST_DISEASES.map(d => d.id);
        const batchResults = await PytorchBridge.predictBatch(imageUri, diseaseIds);
        for (const r of batchResults) {
          const d = CHEST_DISEASES.find(x => x.id === r.disease);
          results.push({
            disease: d?.label || r.disease, id: r.disease, prob: r.probability,
            isPositive: r.prediction === 'POSITIVE', confidence: (r.probability * 100).toFixed(1),
            region: generateRegions(d || { category: 'Chest X-Ray' })[0], onDevice: true,
          });
          setBatchResults([...results]);
        }
      } catch (e) {
        Alert.alert('Batch Error', e.message);
      }
    } else {
      // Demo fallback
      for (const d of CHEST_DISEASES) {
        await sleep(200);
        const prob = Math.random();
        results.push({ disease: d.label, id: d.id, prob, isPositive: prob > 0.5,
          confidence: (prob * 100).toFixed(1), region: generateRegions(d)[0], onDevice: false });
        setBatchResults([...results]);
      }
    }
    setIsBatching(false);
  };

  // ── PDF Export ──
  const exportPDF = async () => {
    if (!report) return;
    try {
      // Convert image to base64 for embedding in PDF
      let imageBase64 = null;
      if (imageUri) {
        try {
          const filePath = imageUri.startsWith('file://') ? imageUri.replace('file://', '') : imageUri;
          imageBase64 = await RNFS.readFile(filePath, 'base64');
        } catch (imgErr) {
          console.log('Could not read image for PDF:', imgErr.message);
        }
      }

      // Get disease encyclopedia info for public mode
      const diseaseInfo = selectedDisease ? DISEASE_INFO[selectedDisease.id] : null;

      // Add tier info from selected disease to report
      const enrichedReport = { ...report, tier: selectedDisease?.tier };

      // Read heatmap images for professional mode
      let camBase64 = null, occBase64 = null;
      if (userMode === 'professional') {
        try {
          if (camHeatmapUri) {
            const camPath = camHeatmapUri.replace('file://', '');
            camBase64 = await RNFS.readFile(camPath, 'base64');
          }
          if (occHeatmapUri) {
            const occPath = occHeatmapUri.replace('file://', '');
            occBase64 = await RNFS.readFile(occPath, 'base64');
          }
        } catch (hErr) { console.log('Heatmap read error:', hErr.message); }
      }

      const html = buildReportHTML(enrichedReport, t, userMode, imageBase64, diseaseInfo, camBase64, occBase64);
      const { uri } = await Print.printToFileAsync({ html, base64: false });
      const shareUri = uri.startsWith('file://') ? uri : 'file://' + uri;
      if (await Sharing.isAvailableAsync()) {
        await Sharing.shareAsync(shareUri, { mimeType: 'application/pdf', dialogTitle: 'Share Diagnostic Report' });
      } else {
        Alert.alert('PDF Saved', `Report saved to:\n${uri}`);
      }
    } catch (e) { Alert.alert('Export Error', e.message); }
  };

  const stepIcon = (s) => s === 'running' ? '⏳' : s === 'done' ? '✅' : s === 'warn' ? '⚠️' : 'ℹ️';

  // ═══════════════════════════════════════════════════════════════════════════
  // ONBOARDING SCREEN
  // ═══════════════════════════════════════════════════════════════════════════
  if (screen === 'onboarding') {
    return (
      <View style={[ss.safe, { backgroundColor: BG }]}>
        <StatusBar barStyle="light-content" backgroundColor={BG} />
        <View style={{ flex: 1, justifyContent: 'center', padding: 24 }}>
          <Text style={{ fontSize: 48, textAlign: 'center', marginBottom: 16 }}>🧠</Text>
          <Text style={{ fontSize: FS_TITLE, fontWeight: '800', color: TEXT1, textAlign: 'center' }}>{t.onboardTitle}</Text>
          <Text style={{ fontSize: FS_BASE, color: TEXT3, textAlign: 'center', marginTop: 8, marginBottom: 40 }}>{t.onboardSub}</Text>

          <TouchableOpacity style={{ backgroundColor: '#1565C0', borderRadius: 16, padding: 24, marginBottom: 16 }}
            onPress={() => { setUserMode('professional'); setScreen('main'); }}>
            <Text style={{ fontSize: 20, fontWeight: '800', color: '#fff' }}>🩺  {t.professional}</Text>
            <Text style={{ fontSize: FS_BASE, color: '#bbdefb', marginTop: 4 }}>{t.profDesc}</Text>
          </TouchableOpacity>

          <TouchableOpacity style={{ backgroundColor: '#00897B', borderRadius: 16, padding: 24 }}
            onPress={() => { setUserMode('public'); setScreen('main'); }}>
            <Text style={{ fontSize: 20, fontWeight: '800', color: '#fff' }}>👤  {t.general}</Text>
            <Text style={{ fontSize: FS_BASE, color: '#b2dfdb', marginTop: 4 }}>{t.genDesc}</Text>
          </TouchableOpacity>
        </View>
      </View>
    );
  }

  // ═══════════════════════════════════════════════════════════════════════════
  // FEATURE 1: HISTORY SCREEN
  // ═══════════════════════════════════════════════════════════════════════════
  if (screen === 'history') {
    return (
      <View style={[ss.safe, { backgroundColor: BG }]}>
        <StatusBar barStyle="light-content" backgroundColor={BG} />
        <ScrollView style={{ flex: 1 }} contentContainerStyle={{ padding: 16 }}>
          <TouchableOpacity onPress={() => setScreen('main')}>
            <Text style={{ color: ACCENT, fontSize: FS_BODY, fontWeight: '700', marginBottom: 16 }}>{t.back}</Text>
          </TouchableOpacity>
          <Text style={{ fontSize: FS_LABEL, fontWeight: '700', color: TEXT3, letterSpacing: 1.2, marginBottom: 16 }}>{t.history}</Text>

          {scanHistory.length === 0 ? (
            <Text style={{ color: TEXT3, fontSize: FS_BASE, textAlign: 'center', marginTop: 60 }}>{t.noHistory}</Text>
          ) : scanHistory.map((item, i) => (
            <View key={item.id || i} style={{ backgroundColor: CARD_BG, borderRadius: 12, padding: 14, marginBottom: 10, borderWidth: 1, borderColor: BORDER }}>
              <View style={{ flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }}>
                <Text style={{ color: TEXT1, fontSize: FS_BODY, fontWeight: '700', flex: 1 }}>{item.disease}</Text>
                <View style={{ backgroundColor: item.prediction === 'POSITIVE' ? '#7f1d1d' : '#14532d', borderRadius: 6, paddingHorizontal: 10, paddingVertical: 4 }}>
                  <Text style={{ color: '#fff', fontSize: 11, fontWeight: '800' }}>{item.prediction}</Text>
                </View>
              </View>
              <View style={{ flexDirection: 'row', justifyContent: 'space-between', marginTop: 6 }}>
                <Text style={{ color: TEXT3, fontSize: 12 }}>{item.category}</Text>
                <Text style={{ color: TEXT3, fontSize: 12 }}>{item.confidence}%</Text>
                <Text style={{ color: TEXT3, fontSize: 12 }}>{new Date(item.date).toLocaleDateString()}</Text>
              </View>
            </View>
          ))}
        </ScrollView>
      </View>
    );
  }

  // ═══════════════════════════════════════════════════════════════════════════
  // SETTINGS SCREEN
  // ═══════════════════════════════════════════════════════════════════════════
  if (screen === 'settings') {
    return (
      <View style={[ss.safe, { backgroundColor: BG }]}>
        <StatusBar barStyle="light-content" backgroundColor={BG} />
        <ScrollView style={{ flex: 1 }} contentContainerStyle={{ padding: 16 }}>
          <TouchableOpacity onPress={() => setScreen('main')}>
            <Text style={{ color: ACCENT, fontSize: FS_BODY, fontWeight: '700', marginBottom: 16 }}>{t.back}</Text>
          </TouchableOpacity>
          <Text style={{ fontSize: FS_LABEL, fontWeight: '700', color: TEXT3, letterSpacing: 1.2, marginBottom: 20 }}>{t.settings}</Text>

          {/* User Mode */}
          <View style={{ backgroundColor: CARD_BG, borderRadius: 12, padding: 16, marginBottom: 12, borderWidth: 1, borderColor: BORDER }}>
            <Text style={{ color: TEXT1, fontSize: FS_BODY, fontWeight: '700', marginBottom: 12 }}>{t.userMode}</Text>
            <View style={{ flexDirection: 'row', gap: 10 }}>
              <TouchableOpacity onPress={() => setUserMode('professional')}
                style={{ flex: 1, padding: 12, borderRadius: 10, backgroundColor: userMode === 'professional' ? '#1565C0' : '#0f172a', borderWidth: 1, borderColor: userMode === 'professional' ? '#1565C0' : BORDER }}>
                <Text style={{ color: '#fff', fontWeight: '700', textAlign: 'center' }}>🩺 {t.professional}</Text>
              </TouchableOpacity>
              <TouchableOpacity onPress={() => setUserMode('public')}
                style={{ flex: 1, padding: 12, borderRadius: 10, backgroundColor: userMode === 'public' ? '#00897B' : '#0f172a', borderWidth: 1, borderColor: userMode === 'public' ? '#00897B' : BORDER }}>
                <Text style={{ color: '#fff', fontWeight: '700', textAlign: 'center' }}>👤 {t.general}</Text>
              </TouchableOpacity>
            </View>
          </View>

          {/* Language */}
          <View style={{ backgroundColor: CARD_BG, borderRadius: 12, padding: 16, marginBottom: 12, borderWidth: 1, borderColor: BORDER }}>
            <Text style={{ color: TEXT1, fontSize: FS_BODY, fontWeight: '700', marginBottom: 12 }}>{t.language}</Text>
            <View style={{ flexDirection: 'row', flexWrap: 'wrap', gap: 8 }}>
              {Object.keys(LANG_LABELS).map(lk => (
                <TouchableOpacity key={lk} onPress={() => setLang(lk)}
                  style={{ paddingHorizontal: 16, paddingVertical: 10, borderRadius: 10, backgroundColor: lang === lk ? ACCENT : '#0f172a', borderWidth: 1, borderColor: lang === lk ? ACCENT : BORDER }}>
                  <Text style={{ color: '#fff', fontWeight: '700' }}>{LANG_LABELS[lk]}</Text>
                </TouchableOpacity>
              ))}
            </View>
          </View>

          {/* Toggles */}
          {[
            { label: t.darkMode, icon: '🌙', val: oledMode, set: setOledMode },
            { label: t.largeText, icon: '🔤', val: largeText, set: setLargeText },
            { label: t.highContrast, icon: '◐', val: highContrast, set: setHighContrast },
          ].map((item, i) => (
            <View key={i} style={{ backgroundColor: CARD_BG, borderRadius: 12, padding: 16, marginBottom: 12, borderWidth: 1, borderColor: BORDER, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }}>
              <Text style={{ color: TEXT1, fontSize: FS_BODY, fontWeight: '600' }}>{item.icon}  {item.label}</Text>
              <Switch value={item.val} onValueChange={item.set} trackColor={{ true: ACCENT }} thumbColor="#fff" />
            </View>
          ))}
        </ScrollView>
      </View>
    );
  }

  // ═══════════════════════════════════════════════════════════════════════════
  // FEATURE 3: ENCYCLOPEDIA SCREEN
  // ═══════════════════════════════════════════════════════════════════════════
  if (screen === 'encyclopedia') {
    return (
      <View style={[ss.safe, { backgroundColor: BG }]}>
        <StatusBar barStyle="light-content" backgroundColor={BG} />
        <ScrollView style={{ flex: 1 }} contentContainerStyle={{ padding: 16 }}>
          <TouchableOpacity onPress={() => { setScreen('main'); setSelectedEncDisease(null); }}>
            <Text style={{ color: ACCENT, fontSize: FS_BODY, fontWeight: '700', marginBottom: 16 }}>{t.back}</Text>
          </TouchableOpacity>
          <Text style={{ fontSize: FS_LABEL, fontWeight: '700', color: TEXT3, letterSpacing: 1.2, marginBottom: 16 }}>{t.encyclopedia}</Text>

          {selectedEncDisease && DISEASE_INFO[selectedEncDisease] ? (
            <View style={{ backgroundColor: CARD_BG, borderRadius: 14, padding: 18, borderWidth: 1, borderColor: BORDER }}>
              <TouchableOpacity onPress={() => setSelectedEncDisease(null)}>
                <Text style={{ color: ACCENT, fontSize: FS_BASE, marginBottom: 12 }}>{t.back}</Text>
              </TouchableOpacity>
              <Text style={{ fontSize: FS_TITLE - 4, fontWeight: '800', color: TEXT1, marginBottom: 16 }}>
                {DISEASE_INFO[selectedEncDisease].name}
              </Text>
              {[
                [t.whatIsIt, DISEASE_INFO[selectedEncDisease].what],
                [t.symptoms, DISEASE_INFO[selectedEncDisease].symptoms],
                [t.riskFactors, DISEASE_INFO[selectedEncDisease].risk],
                [t.severity, DISEASE_INFO[selectedEncDisease].severity],
                [t.nextSteps, DISEASE_INFO[selectedEncDisease].next],
              ].map(([heading, body], i) => (
                <View key={i} style={{ marginBottom: 14 }}>
                  <Text style={{ color: ACCENT, fontSize: FS_BODY, fontWeight: '700', marginBottom: 4 }}>{heading}</Text>
                  <Text style={{ color: TEXT2, fontSize: FS_BODY, lineHeight: FS_BODY * 1.6 }}>{body}</Text>
                </View>
              ))}
            </View>
          ) : (
            Object.keys(DISEASE_INFO).map(did => (
              <TouchableOpacity key={did} onPress={() => setSelectedEncDisease(did)}
                style={{ backgroundColor: CARD_BG, borderRadius: 12, padding: 14, marginBottom: 8, borderWidth: 1, borderColor: BORDER, flexDirection: 'row', alignItems: 'center', gap: 12 }}>
                <View style={{ width: 10, height: 10, borderRadius: 5, backgroundColor: CATEGORY_COLORS[DISEASES.find(d => d.id === did)?.category] || '#64748b' }} />
                <View style={{ flex: 1 }}>
                  <Text style={{ color: TEXT1, fontSize: FS_BODY, fontWeight: '700' }}>{DISEASE_INFO[did].name}</Text>
                  <Text style={{ color: TEXT3, fontSize: 12, marginTop: 2 }} numberOfLines={1}>{DISEASE_INFO[did].what}</Text>
                </View>
                <Text style={{ color: TEXT3, fontSize: 18 }}>›</Text>
              </TouchableOpacity>
            ))
          )}
        </ScrollView>
      </View>
    );
  }

  // ═══════════════════════════════════════════════════════════════════════════
  // FEATURE 10: QUICK COMPARE MODAL
  // ═══════════════════════════════════════════════════════════════════════════
  // Load reference image when compare modal opens
  const openCompare = async () => {
    setShowCompare(true);
    setCompareIdx(0);
    setRefImageUri(null);
    if (PytorchBridge && selectedDisease) {
      try {
        setRefImageLoading(true);
        const uri = await PytorchBridge.getReferenceImage(selectedDisease.id);
        setRefImageUri(uri);
      } catch (e) {
        Log && console.log('Ref image load failed:', e);
      } finally {
        setRefImageLoading(false);
      }
    }
  };

  const CompareModal = () => (
    <Modal visible={showCompare} animationType="slide" transparent>
      <View style={{ flex: 1, backgroundColor: 'rgba(0,0,0,0.95)', justifyContent: 'center', padding: 20 }}>
        <Text style={{ color: '#fff', fontSize: FS_TITLE - 2, fontWeight: '800', textAlign: 'center', marginBottom: 8 }}>{t.compareView}</Text>
        <Text style={{ color: TEXT3, fontSize: FS_BASE, textAlign: 'center', marginBottom: 20 }}>{t.compareHint}</Text>

        <View style={{ flexDirection: 'row', justifyContent: 'center', gap: 16, marginBottom: 16 }}>
          <TouchableOpacity onPress={() => setCompareIdx(0)} style={{ paddingHorizontal: 20, paddingVertical: 8, borderRadius: 20, backgroundColor: compareIdx === 0 ? ACCENT : '#334155' }}>
            <Text style={{ color: '#fff', fontWeight: '700' }}>{t.yourScan}</Text>
          </TouchableOpacity>
          <TouchableOpacity onPress={() => setCompareIdx(1)} style={{ paddingHorizontal: 20, paddingVertical: 8, borderRadius: 20, backgroundColor: compareIdx === 1 ? '#ef4444' : '#334155' }}>
            <Text style={{ color: '#fff', fontWeight: '700' }}>{t.refPositive}</Text>
          </TouchableOpacity>
        </View>

        <View style={{ height: 340, backgroundColor: '#111', borderRadius: 12, justifyContent: 'center', alignItems: 'center', overflow: 'hidden' }}>
          {compareIdx === 0 ? (
            imageUri ? (
              <Image source={{ uri: imageUri }} style={{ width: '100%', height: '100%' }} resizeMode="contain" />
            ) : (
              <View style={{ alignItems: 'center' }}>
                <Text style={{ fontSize: 48 }}>📷</Text>
                <Text style={{ color: TEXT3, marginTop: 8, fontSize: FS_BASE }}>No scan loaded</Text>
              </View>
            )
          ) : (
            refImageLoading ? (
              <View style={{ alignItems: 'center' }}>
                <ActivityIndicator size="large" color={ACCENT} />
                <Text style={{ color: TEXT3, marginTop: 12 }}>Loading reference image...</Text>
              </View>
            ) : refImageUri ? (
              <View style={{ width: '100%', height: '100%' }}>
                <Image source={{ uri: refImageUri }} style={{ width: '100%', height: '100%' }} resizeMode="contain" />
                <View style={{ position: 'absolute', top: 8, left: 8, backgroundColor: 'rgba(239,68,68,0.9)', paddingHorizontal: 10, paddingVertical: 4, borderRadius: 6 }}>
                  <Text style={{ color: '#fff', fontSize: 11, fontWeight: '800' }}>✓ VERIFIED POSITIVE</Text>
                </View>
                <View style={{ position: 'absolute', bottom: 0, left: 0, right: 0, backgroundColor: 'rgba(0,0,0,0.75)', padding: 10 }}>
                  <Text style={{ color: '#f87171', fontSize: 13, fontWeight: '700' }}>{selectedDisease?.label || 'Unknown'}</Text>
                  <Text style={{ color: '#94a3b8', fontSize: 11, marginTop: 2 }}>Reference case from validated test set</Text>
                </View>
              </View>
            ) : (
              <View style={{ alignItems: 'center', padding: 20 }}>
                <Text style={{ fontSize: 48 }}>🔬</Text>
                <Text style={{ color: TEXT3, marginTop: 8, fontSize: FS_BASE, textAlign: 'center' }}>Reference image not available for this disease</Text>
              </View>
            )
          )}
        </View>

        <TouchableOpacity onPress={() => setShowCompare(false)} style={{ marginTop: 20, padding: 16, backgroundColor: ACCENT, borderRadius: 12, alignItems: 'center' }}>
          <Text style={{ color: '#fff', fontSize: FS_BODY, fontWeight: '700' }}>Close</Text>
        </TouchableOpacity>
      </View>
    </Modal>
  );

  // ═══════════════════════════════════════════════════════════════════════════
  // FEATURE 2: CAMERA GUIDE OVERLAY MODAL
  // ═══════════════════════════════════════════════════════════════════════════
  const CameraGuideModal = () => (
    <Modal visible={showCameraGuide} animationType="fade" transparent>
      <View style={{ flex: 1, backgroundColor: 'rgba(0,0,0,0.85)', justifyContent: 'center', alignItems: 'center', padding: 30 }}>
        <View style={{ width: 260, height: 260, borderWidth: 3, borderColor: '#14b8a6', borderRadius: selectedDisease?.category === 'Dermatology' ? 130 : 20, borderStyle: 'dashed', justifyContent: 'center', alignItems: 'center', marginBottom: 20 }}>
          <Text style={{ fontSize: 48 }}>
            {selectedDisease?.category === 'Dermatology' ? '🔵' : selectedDisease?.category === 'Ophthalmology' ? '👁️' : '🫁'}
          </Text>
          <Text style={{ color: '#14b8a6', fontSize: 14, fontWeight: '700', marginTop: 12, textAlign: 'center' }}>
            {selectedDisease?.category === 'Dermatology' ? 'Place lesion in circle' :
             selectedDisease?.category === 'Ophthalmology' ? 'Center eye in frame' :
             selectedDisease?.category === 'Neurology' ? 'Position MRI slice' :
             'Center chest in frame'}
          </Text>
        </View>
        <Text style={{ color: '#94a3b8', fontSize: 13, textAlign: 'center', marginBottom: 20 }}>
          Ensure good lighting. Hold device steady.{'\n'}Image should be clear and focused.
        </Text>
        <View style={{ flexDirection: 'row', gap: 12 }}>
          <TouchableOpacity onPress={() => setShowCameraGuide(false)} style={{ padding: 14, backgroundColor: '#334155', borderRadius: 10, flex: 1, alignItems: 'center' }}>
            <Text style={{ color: '#fff', fontWeight: '700' }}>Cancel</Text>
          </TouchableOpacity>
          <TouchableOpacity onPress={() => { setShowCameraGuide(false); pickImage(true); }} style={{ padding: 14, backgroundColor: '#14b8a6', borderRadius: 10, flex: 1, alignItems: 'center' }}>
            <Text style={{ color: '#fff', fontWeight: '700' }}>📸 Capture</Text>
          </TouchableOpacity>
        </View>
      </View>
    </Modal>
  );

  // ═══════════════════════════════════════════════════════════════════════════
  // MAIN SCREEN
  // ═══════════════════════════════════════════════════════════════════════════
  return (
    <View style={[ss.safe, { backgroundColor: BG }]}>
      <StatusBar barStyle="light-content" backgroundColor={BG} />
      <CompareModal />
      <CameraGuideModal />
      <ScrollView ref={scrollRef} style={{ flex: 1 }} contentContainerStyle={{ padding: 16, paddingTop: 20 }} keyboardShouldPersistTaps="handled">
        <Animated.View style={{ opacity: fadeAnim }}>
          {/* ── Header ── */}
          <View style={{ flexDirection: 'row', alignItems: 'center', marginBottom: 16 }}>
            <Text style={{ fontSize: 32, marginRight: 14 }}>🧠</Text>
            <View style={{ flex: 1 }}>
              <Text style={{ fontSize: FS_TITLE, fontWeight: '800', color: TEXT1 }}>{t.appTitle}</Text>
              <Text style={{ fontSize: FS_BASE, color: TEXT3, marginTop: 2 }}>{t.appSub}</Text>
            </View>
          </View>

          {/* ── Mode indicator bar ── */}
          <View style={{ backgroundColor: ACCENT, borderRadius: 8, padding: 6, marginBottom: 16, alignItems: 'center' }}>
            <Text style={{ color: '#fff', fontSize: 11, fontWeight: '700', letterSpacing: 0.5 }}>
              {userMode === 'professional' ? '🩺 CLINICAL MODE' : '👤 PUBLIC MODE'} · {LANG_LABELS[lang]}
            </Text>
          </View>

          {/* ── Nav Bar ── */}
          <View style={{ flexDirection: 'row', marginBottom: 16, gap: 8 }}>
            {[
              { icon: '📋', label: t.history, target: 'history' },
              { icon: '📖', label: t.encyclopedia, target: 'encyclopedia' },
              { icon: '⚙️', label: t.settings, target: 'settings' },
            ].map(nav => (
              <TouchableOpacity key={nav.target} onPress={() => setScreen(nav.target)}
                style={{ flex: 1, backgroundColor: CARD_BG, borderRadius: 10, padding: 10, alignItems: 'center', borderWidth: 1, borderColor: BORDER }}>
                <Text style={{ fontSize: 18 }}>{nav.icon}</Text>
                <Text style={{ color: TEXT2, fontSize: 10, fontWeight: '600', marginTop: 2 }}>{nav.label}</Text>
              </TouchableOpacity>
            ))}
          </View>

          {/* ── Image Viewer ── */}
          <View style={{ backgroundColor: CARD_BG, borderRadius: 16, padding: 18, marginBottom: 16, borderWidth: 1, borderColor: BORDER }}>
            <Text style={{ fontSize: FS_LABEL, fontWeight: '700', color: TEXT3, letterSpacing: 1.2, marginBottom: 12 }}>{t.medicalScan}</Text>
            <View style={{ height: 260, backgroundColor: oledMode ? '#000' : '#0f172a', borderRadius: 12, overflow: 'hidden', justifyContent: 'center', alignItems: 'center' }}>
              {imageUri ? (
                <Image source={{ uri: imageUri }} style={{ width: '100%', height: '100%' }} resizeMode="contain" />
              ) : (
                <View style={{ alignItems: 'center' }}>
                  <Text style={{ fontSize: 48, marginBottom: 12 }}>📷</Text>
                  <Text style={{ color: TEXT2, fontSize: FS_BODY, fontWeight: '600' }}>{t.noScan}</Text>
                  <Text style={{ color: TEXT3, fontSize: FS_BASE, marginTop: 4 }}>{t.selectHint}</Text>
                </View>
              )}
            </View>
            <View style={{ flexDirection: 'row', marginTop: 12, gap: 10 }}>
              <TouchableOpacity style={{ flex: 1, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', backgroundColor: '#334155', paddingVertical: 10, borderRadius: 10, gap: 6 }} onPress={() => pickImage(false)}>
                <Text style={{ fontSize: 16 }}>🖼️</Text>
                <Text style={{ color: TEXT1, fontSize: FS_BODY, fontWeight: '600' }}>{t.gallery}</Text>
              </TouchableOpacity>
              {/* FEATURE 2: Camera with guide overlay */}
              <TouchableOpacity style={{ flex: 1, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', backgroundColor: '#334155', paddingVertical: 10, borderRadius: 10, gap: 6 }} onPress={() => setShowCameraGuide(true)}>
                <Text style={{ fontSize: 16 }}>📸</Text>
                <Text style={{ color: TEXT1, fontSize: FS_BODY, fontWeight: '600' }}>{t.camera}</Text>
              </TouchableOpacity>
              {imageUri && (
                <TouchableOpacity style={{ flex: 0.6, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', backgroundColor: '#7f1d1d', paddingVertical: 10, borderRadius: 10, gap: 6 }} onPress={() => { setImageUri(null); setPipelineSteps([]); setReport(null); setBatchResults([]); }}>
                  <Text style={{ fontSize: 16 }}>✕</Text>
                  <Text style={{ color: '#fca5a5', fontSize: FS_BODY, fontWeight: '600' }}>{t.clear}</Text>
                </TouchableOpacity>
              )}
            </View>
          </View>

          {/* ── Disease Selector ── */}
          <View style={{ backgroundColor: CARD_BG, borderRadius: 16, padding: 18, marginBottom: 16, borderWidth: 1, borderColor: BORDER, zIndex: 100 }}>
            <Text style={{ fontSize: FS_LABEL, fontWeight: '700', color: TEXT3, letterSpacing: 1.2, marginBottom: 12 }}>{t.diagTarget}</Text>
            <View style={{ flexDirection: 'row', alignItems: 'center', backgroundColor: oledMode ? '#000' : '#0f172a', borderRadius: 12, borderWidth: 1, borderColor: BORDER, paddingHorizontal: 12 }}>
              <Text style={{ fontSize: 16, marginRight: 8 }}>🔍</Text>
              <TextInput style={{ flex: 1, color: TEXT1, fontSize: FS_BODY + 1, paddingVertical: 12 }}
                placeholder={t.searchPlaceholder} placeholderTextColor={TEXT3}
                value={searchQuery} onChangeText={handleSearch} onFocus={() => handleSearch(searchQuery)} />
              {searchQuery.length > 0 && (
                <TouchableOpacity onPress={() => { setSearchQuery(''); setSelectedDisease(null); setShowDropdown(false); }}>
                  <Text style={{ color: TEXT2, fontSize: 18, padding: 4 }}>✕</Text>
                </TouchableOpacity>
              )}
            </View>

            {selectedDisease && (
              <View style={{ marginTop: 12, backgroundColor: oledMode ? '#000' : '#0f172a', borderRadius: 10, borderWidth: 1.5, borderColor: CATEGORY_COLORS[selectedDisease.category] || TEXT3, padding: 12 }}>
                <View style={{ flexDirection: 'row', alignItems: 'center', gap: 10 }}>
                  <View style={{ width: 10, height: 10, borderRadius: 5, backgroundColor: CATEGORY_COLORS[selectedDisease.category] }} />
                  <Text style={{ color: TEXT1, fontSize: FS_BODY + 1, fontWeight: '700', flex: 1 }}>{selectedDisease.label}</Text>
                  <View style={{ backgroundColor: selectedDisease.tier === 'T1' ? '#166534' : selectedDisease.tier === 'T2' ? '#92400e' : '#991b1b', paddingHorizontal: 8, paddingVertical: 3, borderRadius: 6 }}>
                    <Text style={{ color: '#fff', fontSize: 10, fontWeight: '800' }}>{selectedDisease.tier} · AUC {selectedDisease.auc?.toFixed(2)}</Text>
                  </View>
                </View>
                {selectedDisease.caution && (
                  <View style={{ flexDirection: 'row', alignItems: 'center', marginTop: 8, backgroundColor: '#451a0355', borderRadius: 8, padding: 8, gap: 6 }}>
                    <Text style={{ fontSize: 14 }}>⚠️</Text>
                    <Text style={{ color: '#fbbf24', fontSize: 11, flex: 1 }}>{selectedDisease.caution}</Text>
                  </View>
                )}
              </View>
            )}

            {showDropdown && !selectedDisease && filteredDiseases.length > 0 && (
              <ScrollView style={{ marginTop: 8, backgroundColor: oledMode ? '#000' : '#0f172a', borderRadius: 12, borderWidth: 1, borderColor: BORDER, maxHeight: 220 }} nestedScrollEnabled keyboardShouldPersistTaps="handled">
                {filteredDiseases.map((item, index) => (
                  <View key={item.id}>
                    {index > 0 && <View style={{ height: 1, backgroundColor: CARD_BG }} />}
                    <TouchableOpacity style={{ flexDirection: 'row', alignItems: 'center', padding: 12, paddingHorizontal: 14, gap: 10 }} onPress={() => selectDisease(item)}>
                      <View style={{ width: 10, height: 10, borderRadius: 5, backgroundColor: CATEGORY_COLORS[item.category] || TEXT3 }} />
                      <View style={{ flex: 1 }}>
                        <Text style={{ color: item.tier === 'T3' ? '#fbbf24' : TEXT1, fontSize: FS_BODY, fontWeight: '600' }}>{item.tier === 'T3' ? '⚠ ' : ''}{item.label}</Text>
                        <Text style={{ color: TEXT3, fontSize: 12, marginTop: 1 }}>{item.category} · AUC {item.auc?.toFixed(2)}</Text>
                      </View>
                      <View style={{ backgroundColor: item.tier === 'T1' ? '#166534' : item.tier === 'T2' ? '#92400e' : '#991b1b', paddingHorizontal: 6, paddingVertical: 2, borderRadius: 4 }}>
                        <Text style={{ color: '#fff', fontSize: 9, fontWeight: '800' }}>{item.tier}</Text>
                      </View>
                    </TouchableOpacity>
                  </View>
                ))}
              </ScrollView>
            )}
            {showDropdown && !selectedDisease && filteredDiseases.length === 0 && searchQuery.length > 0 && (
              <View style={{ marginTop: 8, backgroundColor: oledMode ? '#000' : '#0f172a', borderRadius: 12, borderWidth: 1, borderColor: BORDER }}>
                <Text style={{ color: TEXT3, fontSize: FS_BODY, textAlign: 'center', padding: 20 }}>{t.noResults}</Text>
              </View>
            )}
          </View>

          {/* ── Run Button ── */}
          <TouchableOpacity style={{ backgroundColor: isProcessing ? '#334155' : ACCENT_BTN, borderRadius: 14, paddingVertical: 16, alignItems: 'center', marginBottom: 16, ...(isProcessing ? {} : { shadowColor: ACCENT_BTN, shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.35, shadowRadius: 12, elevation: 8 }) }}
            onPress={runPipeline} disabled={isProcessing} activeOpacity={0.8}>
            {isProcessing ? (
              <View style={{ flexDirection: 'row', alignItems: 'center' }}>
                <ActivityIndicator color="#fff" size="small" />
                <Text style={{ color: '#fff', fontSize: FS_BODY + 3, fontWeight: '800', marginLeft: 8 }}>  {t.processing}</Text>
              </View>
            ) : (
              <View style={{ flexDirection: 'row', alignItems: 'center' }}>
                <Text style={{ fontSize: 20 }}>⚡</Text>
                <Text style={{ color: '#fff', fontSize: FS_BODY + 3, fontWeight: '800' }}> {t.runPipeline}</Text>
              </View>
            )}
          </TouchableOpacity>

          {/* FEATURE 4: Batch Scan Button (Chest X-Ray) */}
          {imageUri && selectedDisease && (selectedDisease.category === 'Chest X-Ray' || selectedDisease.category === 'COVID X-Ray') && !isProcessing && (
            <TouchableOpacity style={{ backgroundColor: '#4338ca', borderRadius: 14, paddingVertical: 14, alignItems: 'center', marginBottom: 16 }}
              onPress={runBatchScan} disabled={isBatching} activeOpacity={0.8}>
              <Text style={{ color: '#fff', fontSize: FS_BODY + 2, fontWeight: '800' }}>
                {isBatching ? '⏳ Scanning...' : t.batchScan}
              </Text>
            </TouchableOpacity>
          )}

          {/* FEATURE 4: Batch Results */}
          {batchResults.length > 0 && (
            <View style={{ backgroundColor: CARD_BG, borderRadius: 16, padding: 18, marginBottom: 16, borderWidth: 1, borderColor: BORDER }}>
              <Text style={{ fontSize: FS_LABEL, fontWeight: '700', color: TEXT3, letterSpacing: 1.2, marginBottom: 12 }}>{t.batchResults}</Text>
              {batchResults.sort((a, b) => b.prob - a.prob).map((r, i) => (
                <View key={r.id} style={{ flexDirection: 'row', alignItems: 'center', paddingVertical: 8, borderBottomWidth: i < batchResults.length - 1 ? 1 : 0, borderBottomColor: BORDER }}>
                  <View style={{ width: 6, height: 6, borderRadius: 3, backgroundColor: r.isPositive ? '#ef4444' : '#22c55e', marginRight: 10 }} />
                  <Text style={{ color: TEXT1, fontSize: FS_BASE, flex: 1, fontWeight: '600' }}>{r.disease}</Text>
                  <ConfidenceMeter probability={r.prob} size={80} />
                </View>
              ))}
            </View>
          )}

          {/* ── Pipeline Console ── */}
          {pipelineSteps.length > 0 && (
            <View style={{ backgroundColor: CARD_BG, borderRadius: 16, padding: 18, marginBottom: 16, borderWidth: 1, borderColor: BORDER }}>
              <Text style={{ fontSize: FS_LABEL, fontWeight: '700', color: TEXT3, letterSpacing: 1.2, marginBottom: 12 }}>{t.pipelineOutput}</Text>
              <View style={{ backgroundColor: oledMode ? '#000' : '#0f172a', borderRadius: 10, padding: 14 }}>
                {pipelineSteps.map((step, i) => (
                  <View key={step.key || i} style={{ flexDirection: 'row', alignItems: 'flex-start', marginBottom: 8, gap: 8 }}>
                    <Text style={{ fontSize: 14, marginTop: 1 }}>{stepIcon(step.status)}</Text>
                    <Text style={{ color: step.status === 'done' ? '#14b8a6' : step.status === 'warn' ? '#f59e0b' : TEXT2, fontSize: FS_BASE, fontFamily: Platform.OS === 'ios' ? 'Menlo' : 'monospace', flex: 1, lineHeight: 20 }}>{step.text}</Text>
                  </View>
                ))}
                {isProcessing && <View style={{ flexDirection: 'row' }}><ActivityIndicator size="small" color="#14b8a6" /></View>}
              </View>
            </View>
          )}

          {/* ── Report Card ── */}
          {report && (
            <View style={{ backgroundColor: CARD_BG, borderRadius: 16, padding: 18, marginBottom: 16, borderWidth: 1, borderColor: BORDER }}>
              <Text style={{ fontSize: FS_LABEL, fontWeight: '700', color: TEXT3, letterSpacing: 1.2, marginBottom: 12 }}>{t.report}</Text>

              {/* Result Badge */}
              <View style={{ backgroundColor: report.prediction === 'POSITIVE' ? '#7f1d1d' : '#14532d', borderRadius: 10, padding: userMode === 'public' ? 20 : 14, alignItems: 'center', marginBottom: 16 }}>
                <Text style={{ color: '#fff', fontSize: userMode === 'public' ? 22 : 17, fontWeight: '800' }}>
                  {report.prediction === 'POSITIVE' ? '⚠️' : '✅'} {report.prediction === 'POSITIVE' ? t.positive : t.negative} — {report.confidence}%
                </Text>
              </View>

              {/* FEATURE 5: Confidence Meter */}
              <ConfidenceMeter probability={rawProb} size={SCREEN_W - 100} isLarge />

              {/* EXPLAINABILITY: Heatmap Viewer (Professional Only) */}
              {userMode === 'professional' && (camHeatmapUri || occHeatmapUri) && (
                <View style={{ marginBottom: 16 }}>
                  <Text style={{ fontSize: FS_LABEL, fontWeight: '700', color: TEXT3, letterSpacing: 1.2, marginBottom: 10 }}>EXPLAINABILITY MAPS</Text>
                  <View style={{ flexDirection: 'row', gap: 6, marginBottom: 10 }}>
                    <TouchableOpacity onPress={() => setHeatmapTab(0)} style={{ flex: 1, paddingVertical: 7, borderRadius: 8, backgroundColor: heatmapTab === 0 ? ACCENT : '#334155', alignItems: 'center' }}>
                      <Text style={{ color: '#fff', fontSize: 11, fontWeight: '700' }}>Original</Text>
                    </TouchableOpacity>
                    {camHeatmapUri && (
                      <TouchableOpacity onPress={() => setHeatmapTab(1)} style={{ flex: 1, paddingVertical: 7, borderRadius: 8, backgroundColor: heatmapTab === 1 ? '#e11d48' : '#334155', alignItems: 'center' }}>
                        <Text style={{ color: '#fff', fontSize: 11, fontWeight: '700' }}>CAM</Text>
                      </TouchableOpacity>
                    )}
                    {occHeatmapUri && (
                      <TouchableOpacity onPress={() => setHeatmapTab(2)} style={{ flex: 1, paddingVertical: 7, borderRadius: 8, backgroundColor: heatmapTab === 2 ? '#d97706' : '#334155', alignItems: 'center' }}>
                        <Text style={{ color: '#fff', fontSize: 11, fontWeight: '700' }}>Occlusion</Text>
                      </TouchableOpacity>
                    )}
                  </View>
                  <View style={{ height: 220, backgroundColor: '#111', borderRadius: 10, overflow: 'hidden', alignItems: 'center', justifyContent: 'center' }}>
                    <Image
                      source={{ uri: heatmapTab === 0 ? imageUri : heatmapTab === 1 ? camHeatmapUri : occHeatmapUri }}
                      style={{ width: '100%', height: '100%' }} resizeMode="contain" />
                    <View style={{ position: 'absolute', top: 6, right: 6, backgroundColor: 'rgba(0,0,0,0.7)', paddingHorizontal: 8, paddingVertical: 3, borderRadius: 4 }}>
                      <Text style={{ color: '#fff', fontSize: 10, fontWeight: '700' }}>
                        {heatmapTab === 0 ? 'ORIGINAL' : heatmapTab === 1 ? 'CLASS ACTIVATION MAP' : 'OCCLUSION SENSITIVITY'}
                      </Text>
                    </View>
                  </View>
                  <Text style={{ color: TEXT3, fontSize: 10, marginTop: 6, textAlign: 'center' }}>
                    {heatmapTab === 1 ? 'Red regions show strongest model activation for this diagnosis' :
                     heatmapTab === 2 ? 'Red regions caused largest confidence drop when masked' : 'Unprocessed patient scan'}
                  </Text>
                </View>
              )}

              {/* Meta */}
              <View style={{ flexDirection: 'row', gap: 10, marginBottom: 16 }}>
                <View style={{ flex: 1, backgroundColor: oledMode ? '#000' : '#0f172a', borderRadius: 10, padding: 12 }}>
                  <Text style={{ fontSize: FS_LABEL, color: TEXT3, fontWeight: '600', textTransform: 'uppercase', letterSpacing: 0.5 }}>{t.target}</Text>
                  <Text style={{ fontSize: FS_BODY, color: TEXT1, fontWeight: '700', marginTop: 4 }}>{selectedDisease?.label}</Text>
                </View>
                <View style={{ flex: 1, backgroundColor: oledMode ? '#000' : '#0f172a', borderRadius: 10, padding: 12 }}>
                  <Text style={{ fontSize: FS_LABEL, color: TEXT3, fontWeight: '600', textTransform: 'uppercase', letterSpacing: 0.5 }}>{t.region}</Text>
                  <Text style={{ fontSize: FS_BODY, color: TEXT1, fontWeight: '700', marginTop: 4 }}>{report.region}</Text>
                </View>
              </View>

              {/* Findings & Impression */}
              <View style={{ marginBottom: 16 }}>
                <Text style={{ fontSize: FS_BODY, fontWeight: '700', color: ACCENT_BTN, marginBottom: 6, textTransform: 'uppercase', letterSpacing: 0.5 }}>{t.findings}</Text>
                <Text style={{ fontSize: FS_BODY, color: '#cbd5e1', lineHeight: FS_BODY * 1.7 }}>{report.findings}</Text>
              </View>
              <View style={{ marginBottom: 16 }}>
                <Text style={{ fontSize: FS_BODY, fontWeight: '700', color: ACCENT_BTN, marginBottom: 6, textTransform: 'uppercase', letterSpacing: 0.5 }}>{t.impression}</Text>
                <Text style={{ fontSize: FS_BODY, color: '#cbd5e1', lineHeight: FS_BODY * 1.7 }}>{report.impression}</Text>
              </View>

              {/* PUBLIC MODE: Disease Info + Tell Doctor */}
              {userMode === 'public' && DISEASE_INFO[selectedDisease?.id] && (
                <View style={{ backgroundColor: oledMode ? '#001' : '#0c1a2e', borderRadius: 10, padding: 14, marginBottom: 16, borderLeftWidth: 3, borderLeftColor: '#00897B' }}>
                  <Text style={{ color: '#00897B', fontSize: FS_BODY, fontWeight: '700', marginBottom: 8 }}>{t.whatIsIt}</Text>
                  <Text style={{ color: TEXT2, fontSize: FS_BASE, lineHeight: FS_BASE * 1.6 }}>{DISEASE_INFO[selectedDisease.id].what}</Text>
                  <Text style={{ color: '#00897B', fontSize: FS_BODY, fontWeight: '700', marginTop: 12, marginBottom: 4 }}>{t.nextSteps}</Text>
                  <Text style={{ color: TEXT2, fontSize: FS_BASE, lineHeight: FS_BASE * 1.6 }}>{DISEASE_INFO[selectedDisease.id].next}</Text>
                  <Text style={{ color: '#00897B', fontSize: FS_BODY, fontWeight: '700', marginTop: 12, marginBottom: 4 }}>{t.tellDoctor}</Text>
                  <Text style={{ color: TEXT2, fontSize: FS_BASE, lineHeight: FS_BASE * 1.6 }}>
                    An AI screening tool indicated a {report.prediction} result for {selectedDisease.label} with {report.confidence}% confidence. Please review this report and advise on next steps.
                  </Text>
                </View>
              )}

              {/* PROFESSIONAL MODE: Clinician Validate/Reject */}
              {userMode === 'professional' && (
                <View style={{ marginBottom: 16 }}>
                  {verdict ? (
                    <View style={{ backgroundColor: verdict === 'validated' ? '#14532d' : '#7f1d1d', borderRadius: 10, padding: 14, alignItems: 'center' }}>
                      <Text style={{ color: '#fff', fontSize: FS_BODY, fontWeight: '800' }}>
                        {verdict === 'validated' ? t.validated : t.rejected}
                      </Text>
                    </View>
                  ) : (
                    <View style={{ flexDirection: 'row', gap: 10 }}>
                      <TouchableOpacity onPress={() => setVerdict('validated')} style={{ flex: 1, backgroundColor: '#14532d', borderRadius: 10, padding: 12, alignItems: 'center' }}>
                        <Text style={{ color: '#fff', fontSize: FS_BODY, fontWeight: '700' }}>{t.validate}</Text>
                      </TouchableOpacity>
                      <TouchableOpacity onPress={() => setVerdict('rejected')} style={{ flex: 1, backgroundColor: '#7f1d1d', borderRadius: 10, padding: 12, alignItems: 'center' }}>
                        <Text style={{ color: '#fff', fontSize: FS_BODY, fontWeight: '700' }}>{t.reject}</Text>
                      </TouchableOpacity>
                    </View>
                  )}
                </View>
              )}

              {/* Disclaimer */}
              <View style={{ backgroundColor: oledMode ? '#111' : '#1a1a2e', borderRadius: 8, padding: 12, borderLeftWidth: 3, borderLeftColor: userMode === 'public' ? '#BF360C' : '#f59e0b', marginBottom: 16 }}>
                <Text style={{ fontSize: 12, color: userMode === 'public' ? '#ff8a65' : TEXT2, lineHeight: 18, fontStyle: 'italic', fontWeight: userMode === 'public' ? '700' : '400' }}>
                  {userMode === 'public' ? t.publicDisclaimer : t.disclaimer}
                </Text>
              </View>

              {/* FEATURE 10: Quick Compare Button */}
              {imageUri && (
                <TouchableOpacity style={{ backgroundColor: '#6d28d9', borderRadius: 12, paddingVertical: 12, alignItems: 'center', marginBottom: 10 }} onPress={openCompare}>
                  <Text style={{ color: '#fff', fontSize: FS_BODY, fontWeight: '700' }}>🔄  {t.compareView}</Text>
                </TouchableOpacity>
              )}

              {/* FEATURE 7: Export & Share Buttons */}
              <TouchableOpacity style={{ backgroundColor: '#1d4ed8', borderRadius: 12, paddingVertical: 14, alignItems: 'center', marginBottom: 10 }} onPress={exportPDF} activeOpacity={0.8}>
                <Text style={{ color: '#fff', fontSize: FS_BODY + 2, fontWeight: '700' }}>{t.exportPdf}</Text>
              </TouchableOpacity>
              <TouchableOpacity style={{ backgroundColor: '#25D366', borderRadius: 12, paddingVertical: 14, alignItems: 'center' }} onPress={exportPDF} activeOpacity={0.8}>
                <Text style={{ color: '#fff', fontSize: FS_BODY + 2, fontWeight: '700' }}>{t.sharePdf}</Text>
              </TouchableOpacity>
            </View>
          )}

          <View style={{ height: 40 }} />
        </Animated.View>
      </ScrollView>
    </View>
  );
}

// ═══════════════════════════════════════════════════════════════════════════════
// MINIMAL STYLES (most styling is inline for theme-awareness)
// ═══════════════════════════════════════════════════════════════════════════════
const ss = StyleSheet.create({
  safe: { flex: 1, paddingTop: StatusBar.currentHeight || 0 },
});
